### ISSUE TITLE
Terminal stopped working following update to Atom 1.12.2

### ISSUE THREAD

**Issue by nschappl** [platformio/platformio-atom-ide-terminal#105]
I can create a new terminal, but I cannot type any shell input or see any shell output. Everything was working well prior to the latest Atom update (1.12.2). I'm on MacOS Sierra 10.12.1.

**Comment by edcolcode** [comment]
The same issue for me :(. I'm using Win10 x64.

**Comment by Fred-Barclay** [comment]
@nschappl Have you updated to the latest platformio-ide-terminal (version 2.2.2)?

**Comment by nschappl** [comment]
@Fred-Barclay Yes, I am currently running platformio-ide-terminal v2.2.2. I've even tried uninstalling and re-installing the package. Today, Atom released another update (v1.12.3). I updated Atom as well, but the problem still persists. I can see the terminal and have a flashing cursor, but the terminal will not take any input.
![screen shot 2016-11-15 at 2 32 10 pm](https://cloud.githubusercontent.com/assets/889753/20320675/b1c4a1d2-ab40-11e6-9d56-e24b656730e7.png)

**Comment by nschappl** [comment]
Here is the error that is thrown as soon as I hit the "+" button to open a new terminal:

![screen shot 2016-11-15 at 2 39 00 pm](https://cloud.githubusercontent.com/assets/889753/20320899/7ca2eb3e-ab41-11e6-82d0-e7c46461134e.png)

**Comment by ivankravets** [comment]
@nschappl what is your defult shell?

**Comment by nschappl** [comment]
Bash

**Comment by arorashivani** [comment]
I was  also facing the same issue, not able to write input or see any output.
Tried uninstalling then installing  and like 90 % of computer problems it worked now everything is back to normal :)

**Comment by nschappl** [comment]
Unfortunately, that did not work for me. I tried uninstalling and re-installing the package. I also restarted Atom itself.

**Comment by welf** [comment]
I have the same problem. 

terminal-plus has stopped working as well.

**Comment by ghost** [comment]
I am having this problem (Mac OS X El Capitan, Atom 1.12.5) but I just discovered that if I run Atom from the command line, platform-ide-terminal works fine. However, it gives the black screen and blinking cursor when I run Atom from the Finder. This smells like an environment variable issue or something. This behavior persisted across a reboot.

**Comment by nschappl** [comment]
I notice the same behavior as @fremder99. If I run Atom from the command line, platform-ide-terminal works as expected. If I run atom any other way, I get a black screen with a blinking cursor that doesn't take input or display output.

**Comment by welf** [comment]
I have solved this problem by upgrading `node` to the version 6.9.1.

**Comment by ghost** [comment]
Interesting, because I have `node` installed from a "pkg" installer that puts it in  the`/usr/local` tree. So, at the command line:

```
% node -v
v6.9.1
```

But Atom for Mac is downloaded and copied into `/Applications`. It contains its own version of `node` (as near as I can tell). Again, from the command line:

```
% atom -v
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
So I have the latest release of Atom, but it uses an old version of `node`internally.

I think when I double-click the Atom app, it uses its internal version of `node`. When I run `atom` at the command line, the `path` environment overrides the Atom-internal, and Atom finds the newer version of `node`, and thus, the platformio-ide-terminal works.

I guess the question is, is there a way to update the Atom-internal version of `node`?

 I'm kinda thinking the developers haven't done so for a reason (things break?), so I (Mac users?) may be confined to using the command line for a while. I've seen some discussions of how to wrap a Mac app in a tiny `bash` script to gain the environment variables, but seems a bit much...

**Comment by nschappl** [comment]
Yeah I'm still witnessing the same behavior as @fremder99.

**Comment by JEDacreWright** [comment]
Do we have any new input ? I too have the same issue since this update.

**Comment by JEDacreWright** [comment]
Having the same behaviour as @fremder99, I tried to open atom with command-line and it did use the correct node version. Thanks for that.
