### ISSUE TITLE
cannot open file in this terminal as before.

### ISSUE THREAD

**Issue by zzploveyou** [platformio/platformio-atom-ide-terminal#106]
type 'atom test.py' cannot work as before.
(platformio-atom-ide-terminal2.2.2)
```
[11:17 ~/program]$ atom --help
Usage: node [options] [ -e script | script.js ] [arguments]
       node debug script.js [arguments]
......
why ???

**Comment by Fred-Barclay** [comment]
@zzploveyou Do you remember the last version of platformio-ide-terminal that you were able to do this with?

**Comment by juriejan** [comment]
This is connected to a problem I was having with running Electron from the terminal that ```platformio-atom-ide``` provides. There is an environment variable called ```ELECTRON_RUN_AS_NODE``` that is set in the terminal's environment that tells Electron to run as Node instance instead of a standard Electron instance (or something like that).

Does anyone know where and why this environment variable gets set for the ```platformio-atom-ide``` terminal?

You can fix this for each terminal you open by using the following command:
```
$ unset ELECTRON_RUN_AS_NODE
```

**Comment by Naki21** [comment]
https://github.com/Fred-Barclay/Termination/issues/33

I think this may be a more permanent fix

**Comment by Fred-Barclay** [comment]
@Naki21 If the solution you provided works for our Issues (which I think it will), I was going to kick the fix back up to the platformio devs. But, since you were the one to notice the root cause and suggest the fix, would you like to open the pull request yourself?
No worries if not - I'll be happy to send in the patched code. :smile: Just let me know if you want to do it yourself or would rather me do it.

**Comment by Naki21** [comment]
@Fred-Barclay 

Sure thing, I can do it.
