### ISSUE TITLE
Can't click buttons in status bar during tooltip transition.

### ISSUE THREAD

**Issue by QuasimodoNZ** [platformio/platformio-atom-ide-terminal#149]
Keyword is _during_.

When attempting to click a button, such as New Terminal, Close All or switching to a different open terminal. I must first wait until the fade in transition on the tooltip has finished, meaning if the mouse release event occurs before this the button is not clicked.

The buttons work fine when I disable the transition from Developer Tools.

**Comment by QuasimodoNZ** [comment]
Well damn, I think it might be from atom-material-ui by silvestreh.

**Comment by kbrgl** [comment]
I've been experiencing the same issue with atom-material-ui. How did you disable the transition from devtools?

EDIT: Nvm, I figured it out. Adding this to my stylesheet fixed the problem:
```css
.tooltip {
  transition: opacity 500ms;
}
```
The problem is that atom-material-ui adds unnecessary transitions to the `transform` property of tooltips. This resets it to only having transitions on the tooltip opacity.

**Comment by erwstout** [comment]
Came here with the same issue, thanks!

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 which since [f64888d](https://github.com/platformio/platformio-atom-ide-terminal/commit/f64888d6d134f7e06bbb13a762dfd45335e8a4ba) is using node-pty-prebuilt instead unmaintained and outdated pty.js. This is good news for stability and compatibility.

if issues persist, please open a new ticket with requested information.

Thx =)
