### ISSUE TITLE
Multiple OS Conflict of Shell Override

### ISSUE THREAD

**Issue by stevenventimiglia** [platformio/platformio-atom-ide-terminal#153]
I would like to see the option of the Shell Override to be cross-compatible between Windows and MacOS environments.  Many users have made Atom their "go to" editor, and I would love to do the same with the platformio-atom-ide-terminal package to access my terminal via Atom.

It currently overwrites those settings when synced between operating systems and it would be preferred if it no longer did that.

You are about to dethrone terminal-plus since it has been marked as deprecated due to the inability to launch the console or update the package.

**Comment by stevenventimiglia** [comment]
I may have jumped the gun on this.  Marking this issue as resolved, and will revisit it if necessary.

**Comment by ryanaltvater** [comment]
@stevenventimiglia Did you figure it out? I just ran into this issue when adding a Windows path to Shell Override, synced my settings up from Windows, synced my settings down to macOS, launched the Atom terminal on macOS and received an error `execvp(3) failed.: No such file or directory` because it was trying to look for the Windows path.

**Comment by stevenventimiglia** [comment]
@ryanaltvater - Unfortunately, I continued to experience far too many issues with the inconsistency of several packages after a major update of Atom (approx. a year ago.)

I now use Visual Studio Code and have experienced zero issues over the last eight months, it includes a terminal w/ the ability to create a list of other terminal flavors that can be launched, as well as a similar 'sync' extension and super-flexible settings (according to the project or workspace you're using.)  They also just added 'Live Share', which allows you to collaborate remotely with colleagues on the same code while watching and titling any changes that are made real-time.

I love and appreciate the work put into Atom over the years, but with Microsoft's acquisition of Github - I honestly think that Atom will go EoL fairly soon, unless VS Code moves to a pay model.  Visual Studio Code is available for Windows, Mac and Linux OSes, as well.

https://code.visualstudio.com/

**Comment by the-j0k3r** [comment]
Atom a year ago and Atom now, two different beasts, I especially liked the sweeping statement that it had zero issues in 8 months, I used it for a week before Atom and gave up.

**Comment by ryanaltvater** [comment]
@stevenventimiglia I'm very familiar with VS Code. I've actually been fiddling around with it here and there, and so far it's not my cup of tea. It may have a few good features implemented that I do give it credit for, 1 being it's autocomplete which I think is a lot better than Atom but other than that nothing else stands out to me (except maybe Terminal which you mentioned and I'll have to check out). Messing with settings is horrendous. The new settings preview isn't really that much of a step up, other than just giving it an initial pass at a GUI implementation. I'm still going to keep it on the back burner and watch its progress over time because I'm curious, but for the last few years and right now Atom has been my jam. It has improved significantly over the last year, to the point that @the-j0k3r made.

Also, I had the same concerns about Atom dying out because of the Micro$oft acquisition, but there was an article/letter (and Reddit thread) released by the GithHub CEO stating that both editors would continue to be supported side by side and Atom would not be killed off or implemented into one another. They believe in Developers choosing whatever editor they want to work with GitHub. That's not to say that in a year or 2 that will change, but as of right now there's no reason to abandon one editor over the other, unless it's regarding features and your preferred workflow. Not because of an acquisition concern that I initially shared as well. I've been through an acquisition in my career and what we were told was a bunch of lies and fluff to keep people happy. They very well "could" put more effort into VS Code and less effort over time into Atom and shift the community's support to VS Code because it doesn't push updates as quick anymore or something bogus like that. It can happen. Until that day, I won't stress the acquisition...but I won't talk highly about it either lol.

**Comment by stevenventimiglia** [comment]
"...and have experienced zero issues over the last eight months", is not a sweeping statement.  It's an accurate statement about my personal experience with VS Code.  Choose your extensions/packages wisely, and more of them seem to be well maintained.

Even the creators of this package have moved on to VS Code...
https://github.com/platformio/platformio-atom-ide-terminal/issues/543

Being a Notepad++ fan forever (and still using it for basic text files these days), and growing to love Atom, I never liked 'opposing choices' like VS Code or Brackets, because I tried both after heavily used packages that I depended on were never updated or maintained for Atom, and still didn't really want to move away from it - however, lots of colleagues started doing so, and I'm glad I did (after a hard fight.)

It's all about personal taste, my friend.  Even if we use the same IDE, there will always be personal tweaks we'll make to it so our preferences and workflow are accommodated.

**Comment by ryanaltvater** [comment]
Absolutely. I can agree with all of that.

**Comment by the-j0k3r** [comment]
> Even the creators of this package have moved on to VS Code...

You know very well that this is the ONLY half decent working (just barely) terminal for Atom, once this goes everyone else will (probably) do the same. Atom team has said they wont maintain a terminal, so VScode may very well be the only choice unless someone grabs it by the horns.

This alone is very sad for opensource and choices, Since Atom team wont develop/maintain a terminal is that not in itself limiting the users and forcing them to VCcode? I think it is.

**Comment by ryanaltvater** [comment]
I agree with you as well. Unfortunately, what’s done is done with the whole acquisition thing. I don’t agree with it, but there’s no way they’ll maintain 2 competing products under the same parent company. Microsoft is in charge now and Code is their baby. They’re not going to abandon it for an open source product like Atom. That’s why I said in a year or 2 things could be a lot different than what the GitHub CEO said recently. His response to developer concerns was basically just damage control in my opinion. They’ll most certainly phase out Atom over time but not by their doing and rather the community’s doing. Plugin developers are going to naturally flock to what they see as longer lasting and in this situation that looks like Code because Microsoft is in charge. Once plugin developers abandon Atom and move to supporting Code instead of Atom or both, you’ll see developers do the same. Therefore, the death of Atom won’t be by Microsoft directly but rather by the community BECAUSE of Microsoft. On their end, it’s a smart move. They’ll continue to support Atom for the foreseeable future (for now) and let he community run its course. Once the community and support for plugins drop off, there you go...Atom will be dead because of the community and Microsoft will just sit back laugh and shut it down. Atom supporters have been shaken up, and you can’t blame them. This is how acquisitions go! Now they (like myself) are questioning whether it’s worth investing in Atom anymore because of the circumstances. I absolutely love Atom, but I can’t stop what now feels like the inevitable because GitHub sold out. So I feel somewhat forced into checking out Code now and possibly switching at some point soon or down the road. :(

**Comment by the-j0k3r** [comment]
I'll just repeat it, Without a n actively maintained terminal to keep up with Atom development, Atom as a viable solution able to compete, its days are numbered.

Sad day for opensource and death of any real innovation.

This reminds me a little in some ways of Novel but only with a spin and a half..

**Comment by the-j0k3r** [comment]
If anyone is interested see https://github.com/atom/atom/issues/17580 It should be interesting to see what will happen to that request and if any healthy outcome will result in something positive, if not for this project for some replacement terminal or ... something else :)
