### ISSUE TITLE
path undefined on Windows, if Atom opened from bash shell

### ISSUE THREAD

**Issue by batjko** [platformio/platformio-atom-ide-terminal#17]
Hi guys,

I realize this is something of a niche scenario, but let me log it anyway:

This is on Windows 10.
When I open atom from the (MINGW64) bash shell that comes with the Docker toolbox (and is required by it, apparently), this package no longer gets the right value for a path and thus panics, yelling `TypeError: Path must be a string. Received undefined`:

![image](https://cloud.githubusercontent.com/assets/7287076/14617916/1082768e-05a8-11e6-9433-8e50db9882ef.png)

Now I think it's even more worth mentioning, given how the [bash shell is coming to Windows 10](http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/) in a few months, and developers will start flocking back to Windows land... I imagine!
##

**Comment by simonjm** [comment]
I ran into the same issue using Cygwin. I noticed [here](https://github.com/platformio/platformio-atom-ide-terminal/blob/590026a4c0ef6e50aa3b07ae068136ccb7289461/lib/platformio-ide-terminal.coffee#L71) the code is expecting the SystemRoot environment variable to be set but under Cygwin SYSTEMROOT is set instead. Not sure the best way to handle this case in the code but as a workaround you could set SystemRoot before running atom like this `SystemRoot=$SYSTEMROOT atom .`

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.

These type issues all so far seem fixed with this release since [f64888d](https://github.com/platformio/platformio-atom-ide-terminal/commit/f64888d6d134f7e06bbb13a762dfd45335e8a4ba) switching to the currently actively maintained node-pty-prebuilt instead unmaintained and outdated pty.js.

This is good news for stability and compatibility.

if issues persist, please open a new ticket with requested information.

Thx =)
