### ISSUE TITLE
How can I change terminal font to Terminus?

### ISSUE THREAD

**Issue by scippio** [platformio/platformio-atom-ide-terminal#212]
How can I change terminal font to Terminus?

**Comment by ingoha** [comment]
(Indirectly) answered here: https://github.com/platformio/platformio-atom-ide-terminal/issues/217

**Comment by deeprave** [comment]
(Long time since this post, however a google search got me here)

The correct answer is not related to this plugins configuration, but Settings->Editor->Font Family.

Simply insert the desired font here, and yes it changes your editing font too, so you should prefer a monospaced font. Since I use [powerline](https://github.com/powerline/powerline) to modify my bash prompt on MacOS, a compatible font is needed in the terminal containing the appropriate symbols in order to render correctly.

**Comment by yodor** [comment]
I have the issue too.
I go to PlatformIO->Settings->PlatformIO IDE Terminal 
Then I input "xos4 Terminus" into Style-> Font Family but font is not changed correctly
:)

**Comment by the-j0k3r** [comment]
@yodor and I assume the font is installed in system and your using the correct font name, right?

I can tell you this works here with Atom 141.0 and Windows 10 PRO 1809 and my fork of this project at https://github.com/bus-stop/terminus/tree/decaffeinated-terminus in Javascript seems to work.

I`ll be testing under macOS and Linux shortly to confirm their correct operation.

Also note that if you dont configure the terminal font or font size the fallback is to What Atom has defined under Atom > Settings > Editor  > Font Family, in this case you can try adding it to Atom instead. Either should work, font being installed and called at the beginning say 

`xos4 Terminus, Menlo, Consolas, DejaVu Sans Mono, monospace` **no quotes around font names** <-  Atom's default font family  + xos4 Terminus prioritized.

Bare in mind adding to Atom will change Editor fonts also

![generic](https://user-images.githubusercontent.com/31389848/68834388-f192d300-06b5-11ea-8e26-99e833e74c0a.gif)

**Comment by the-j0k3r** [comment]
this is a duplicate of #33 #86 #152 #212
