### ISSUE TITLE
Focus Not works after update 2.5.2

### ISSUE THREAD

**Issue by gholami-mohammad** [platformio/platformio-atom-ide-terminal#273]
After update to version 2.5.2 , when press ctrl+` , terminal will open but not focused , focus still is on editor panel.

**Comment by ivankravets** [comment]
The issue is linked with this PR https://github.com/platformio/platformio-atom-ide-terminal/pull/251

@AaronBurmeister could you comment here? Should I revert back your PR?

**Comment by 2manyvcos** [comment]
I'll look into this once I'm at home.
But this should not be very difficult to fix so I think there is no need to revert the PR. What do you think @ivankravets?

**Comment by ivankravets** [comment]
@AaronBurmeister would be thankful if you take a look at this issue and provide new PR.

**Comment by ivankravets** [comment]
@AaronBurmeister could you reproduce this issue? I've just checked and can't reproduce :( 

P.S: @gholami-mohammad could explain in details how to reproduce it?

**Comment by 2manyvcos** [comment]
@ivankravets it always happens when you do not have focus on the console but want it to get focus (`platformio-ide-terminal:focus` or `platformio-ide-terminal:toggle` etc.)

This is because the last active element may be something else than the terminal when executing the command and my fix didn't handle this...

Try something like:
- Open a terminal
- Click on a editor pane so that it has focus
- Execute `platformio-ide-terminal:focus`

**Comment by ivankravets** [comment]
Thanks, released!

* https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.5.3

**Comment by gholami-mohammad** [comment]
Fixed for me! Thanks
