### ISSUE TITLE
Terminal doesn't install all npm modules

### ISSUE THREAD

**Issue by Aghi3** [platformio/platformio-atom-ide-terminal#277]
Hello!
I'm having issues installing all npm modules on my Angular4 project with "npm install". From the first glance it seems like the system variables aren't recognized. I only get 10 or so dmodules in node_modules which are straight from my project file "package.json". In that result I can't serve the app. 

If I run the same command in Win Cmd all the 700+ modules install properly. 
My app can then be served from your terminal once I get all the modules. 

Also the command "ng new <name>" also install just a few modules if that may be of any help. 

Reagrds

**Comment by ghost** [comment]
Did you find a solution @Aghi3

**Comment by Ajedi32** [comment]
I believe I've discovered a possible cause of this. Atom sets the `NODE_ENV` environment variable to "production" when it is starts. Since this terminal inherits its environment from Atom, `NODE_ENV` is also set to "production" within the terminal, meaning `devDependencies` are ignored.

I'm not sure whether this is a problem that should be solved at the package level, or whether we should escalate this upstream.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
