### ISSUE TITLE
Terminal throws winpty.dll error and not responding

### ISSUE THREAD

**Issue by jarig** [platformio/platformio-atom-ide-terminal#311]
Whenever I try open it (no matter what shell I use) it gives exception from winpty.dll and terminal is not usable - 
```
File: ..\..\..\deps\winpty\libwinpty\winpty.cc
Line: 194
Expression: "success && actual == sizeof(int32_t)
```

![image](https://user-images.githubusercontent.com/375519/29174399-e1242afc-7dee-11e7-9510-40499219d156.png)

**Comment by madvlad** [comment]
I'm getting this issue as well.

**Comment by ghost** [comment]
Yeah need help with this one too.

**Comment by Askadar** [comment]
Don't know how, but installing and rebuilding @2.3.1 (I also tried some previous versions to check if the error was introduced in recent builds, I think 2.5.3 and 2.5.1) and then latest version fixed the issue. I've got this error after updating to Atom@1.19.

**Comment by erkobg** [comment]
same here....

**Comment by scotthuang1989** [comment]
any updates on this ? It's a very annoying issue

**Comment by aviadshiber** [comment]
same here

**Comment by the-j0k3r** [comment]
You can also try with a fresh atom configuration as described in the debugging page for atom.

Or  by disabling non core packages one by one testing in between and close reopen a terminal to see if issue persists, until the issue is gone, or you run out of external extension to disable,

If the issue still persists after all that, youre SOL,

These me too reports that raise a year old report and dont provide ANY new information about OS being used, Atom versions or anything useful are the nightmare for anyone trying to help.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
