### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by JustinJohnsonK** [platformio/platformio-atom-ide-terminal#325]
In my windows 10 this terminal is just blinking its cursers without displaying any thing else.
Cant even type anything into it.

**Comment by hollyos** [comment]
+1

With hotkeys or with selecting the option from the drop-down menu the terminal no longer shows in the editor. Using a 2015 MacBook Pro running macOS Sierra V 10.12.6

**Comment by undecided** [comment]
@badwolf7 Came across the same issue as you today, but the following issue has a fix that worked for me - https://github.com/platformio/platformio-atom-ide-terminal/issues/297 (I used Solution 1, it worked perfectly). 

Sorry OP, it might work for you - I don't know, but it sounds like maybe your problem is different

**Comment by hollyos** [comment]
Thanks @undecided Solution 1 worked just fine!

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
