### ISSUE TITLE
how to set terminator as default?

### ISSUE THREAD

**Issue by alziqziq** [platformio/platformio-atom-ide-terminal#384]

**Comment by nitrocode** [comment]
Instead of using an old fork of [term.js](https://github.com/jeremyramin/term.js/) for the plugin's terminal emulator, I wonder if it's possible to use [terminal-kit](https://github.com/cronvel/terminal-kit) as it seems that it supports terminator out of the box and is still maintained.

Also if this is labeled as `PR welcome` then how come it's closed?
