### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by abhijitvernekar** [platformio/platformio-atom-ide-terminal#427]
![capture](https://user-images.githubusercontent.com/32807852/33557755-1b2fce6e-d92e-11e7-8eb0-02689c8286c3.PNG)

**Comment by dunkinman** [comment]
Has this been fixed?  I switched to a new computer today and the only way I can seem to get around it is to reinstall Atom every time I reboot.  Not a great long term solution.

**Comment by dunkinman** [comment]
I'm running Windows 10 pro.  This problem doesn't seem to exist on my other computer where I'm running Windows 10 home.  Perhaps that's part of it?  I'm running 64 bix os x64 based processor.

**Comment by dunkinman** [comment]
Quick update.  Seems to be working today.  I did about 100 restarts yesterday but nothing seemed to fix it.  Today, the only thing that appears to be different is that Atom is loading with a project in it.  Yesterday, it didn't have a project in it because it was a new install.  Today after I loaded a project and did some development for a while, I closed Atom and then reopened it just for fun, cause that's how I roll, and I no longer get the error.  Happy camper for now.

**Comment by dunkinman** [comment]
Another quick update.  Issue persists.  Read on another thread to keep closing terminal and reopen until issue goes away.  Not the most sophisticated approach, but it seems to work.  Don't need to reinstall or anything just close terminal, reopen it, and then issue persists, repeat.  Keep doing this until issue goes away.  Seems to work.

**Comment by felix9ia** [comment]
open Atom by admin?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
