### ISSUE TITLE
(ctrl + L) can not work correctly

### ISSUE THREAD

**Issue by huanggm** [platformio/platformio-atom-ide-terminal#488]
When I press (ctrl + L), no respnse until I press (enter) ,then the terminal clear and print a new line.

**Comment by bentalexanderhaase** [comment]
Same issue here. It has been like this forever.

**Comment by kylemart** [comment]
I also experience this!

**Comment by the-j0k3r** [comment]
This is working fine under

```> apm -v

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 3.5.2
git 2.20.1.windows.1
visual studio

> atom -v

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

platformio-ide-terminal version: 2.9.0
Os Windows 10 pro 1803 build 17134.556
```

Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 which since [f64888d](https://github.com/platformio/platformio-atom-ide-terminal/commit/f64888d6d134f7e06bbb13a762dfd45335e8a4ba) is using node-pty-prebuilt instead unmaintained and outdated pty.js. This is good news for stability and compatibility.

if issues persist, please open a new ticket with requested information.

Thx =)
