### ISSUE TITLE
Clearing the terminal does not work correctly

### ISSUE THREAD

**Issue by piuccio** [platformio/platformio-atom-ide-terminal#502]
Hi, thanks for the package, it's quite nice.

I use it to watch tests running while editing files, and I run `jest --watch` in the terminal.
Jest clears the console on every restart, and that works fine in the standalone terminal, but for some reason it won't clear the terminal inside this atom plugin.

**Comment by the-j0k3r** [comment]
I have some sort of issue with the text not clearing but its unrelated to jest.

![test](https://user-images.githubusercontent.com/31389848/39189793-02235790-47cb-11e8-8464-82beffaa7168.gif)

As you can see towards the end pressing enter and text is sitting in front of prompt from previous buffer?

This example is a very mlld example, and this issue becomes so bad that the whole screen inside terminal if flooded with old text.

Solution is to close that terminal and open another one. Rinse and repeat depending on the amount of work.

@ivankravets  that PR welcome label is very pretty, but it doesnt help if I cant fix it, heck I dont even know what the actual issue is or where it may lie.

Heres some extra info you may find useful.
----

Windows 10 64bit 1709 16299.371
Atom 64bit 1.26.0
Platform-ide-terminal 2.8.1

```
$ atom --version
v7.9.0
```

```
$ apm --version

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python 3.5.2
git 2.17.0.windows.1
visual studio
```
![capture](https://user-images.githubusercontent.com/31389848/39189339-ea5dc204-47c9-11e8-9bf1-99c263cd89f4.PNG)

**Comment by the-j0k3r** [comment]
try again with platformio-atom-ide-terminal 2.9.0 should be all fixed.
