### ISSUE TITLE
Ctrl-C doesn't interrupt

### ISSUE THREAD

**Issue by thiagola92** [platformio/platformio-atom-ide-terminal#510]
Don't know if i should post it here.
Created a loop in lua and started using platformio-ide-terminal to run, notice that i couldn't interrupt using Ctrl-C, the only options was to close the terminal tab.

EDIT:
I was able to stop sometimes pressing a lot of times Ctrl-c and trying to insert text using the button "insert text", but only if i did this at the begining and would take some time to actually stop.  
![example](https://i.imgur.com/0JfBKlB.png)
After this, everything that i pressed/insert appears.

**Comment by the-j0k3r** [comment]
works fine here

Windows 10 64bit 1709 16299.371
Atom 64bit 1.26.0
Platform-ide-terminal 2.8.1

```
$ atom --version
v7.9.0
```

```
$ apm --version

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python 3.5.2
git 2.17.0.windows.1
visual studio
```
![capture](https://user-images.githubusercontent.com/31389848/39189339-ea5dc204-47c9-11e8-9bf1-99c263cd89f4.PNG)

**Comment by thiagola92** [comment]
```
$ apm -v
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.14
git 2.14.1
```

I think that doesn't work when i print to much  
Video example:  
https://www.youtube.com/watch?v=OL2vuf6LdRY

When i don't print anything the ctrl-c work as normal, there is a chance do be my machine that doesn't run so well Atom.

**Comment by the-j0k3r** [comment]
It could be a number of reasons, I see you're using Linux and we dont know what version that is...
That said I also experience some sort of refresh issue when there is too much information processed by platformio-ide-terminal, I feel there must be some sort of buffer that gets corrupted when its filled with a great deal of information. In my case that is manifested like this issue #502 

Unfortunately for us, there is no more development going on with this project, the owner claims he will maintain existing functionality with new versions of atom, but says nothing about bug fixes.
See https://github.com/platformio/platformio-atom-ide-terminal/issues/514#issuecomment-384241678

By the looks of it, with the overwhelming **PR welcome** labelling looks like bug fixes may not even come. So that leaves you and me looking for an alternative or fix it ourselves, I have no idea how to fix it.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 these type issue all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
