### ISSUE TITLE
2.8.1 does not work on Atom 1.26.0 Windows 10 32bit

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#514]
Flashing cursor only, can't type.

2.8.1 does not work on Atom 1.26.0 Windows 10 32bit

**Comment by marjanj** [comment]
same problem on this version !
windows 10 64-bit

**Comment by the-j0k3r** [comment]
Works perfectly fine here:

Windows 10 64bit 1709 16299.371
Atom 64bit 1.26.0
Platform-ide-terminal 2.8.1

```
$ atom --version
v7.9.0
```

```
$ apm --version

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python 3.5.2
git 2.17.0.windows.1
visual studio
```
![capture](https://user-images.githubusercontent.com/31389848/39189339-ea5dc204-47c9-11e8-9bf1-99c263cd89f4.PNG)

![test2](https://user-images.githubusercontent.com/31389848/39189614-8c646d6e-47ca-11e8-9507-615f10c0b414.gif)

**Comment by mdurchholz** [comment]
My instance is also not working. I get a flashing cursor without the ability to type anything.

Atom 1.26.0 Windows 10 64bit

**Comment by the-j0k3r** [comment]
You guys that dont have this working, have you tried uninstalling the platformIO-ide-terminal and reinstalling it again?

What about uninstalling atom and reinstalling it again also?

If not try https://atom.io/packages/termination and see if that fairs better,.

A personal observation about this project, at this rate of labelling by author @ivankravets  **PR Welcome** and amount of commits and activity being minimal, suggests that he is either too busy with real life, or, he is not inclined to invest time on this project investigating and fixing anything himself any time soon. Even the PR's open are months old, so that suggests hes likely too busy to handle the project.

**Comment by ivankravets** [comment]
1. We hope that @github will finally add a built-in terminal to Atom as VSCode did. 
2. We don't plan to develop this package anymore because are working on the moving to VSCode.
3. We are open for PR and will try to maintain existing functionality for the new Atom versions.

/cc @nathansobo @as-cii

**Comment by the-j0k3r** [comment]
> We don't plan to develop this package anymore because are working on the moving to VSCode.

Thanks for the update. it happens, its sad, but it happens,

**Comment by the-j0k3r** [comment]
> We hope that @github will finally add a built-in terminal to Atom as VSCode did.

@ivankravets that will never happen https://github.com/atom/atom/issues/12649

They explicitly said that they wont maintain it, so that leaves us in the dry from both fronts there is currently no maintained versions of a terminal, they are all flaky and buggy as hell this was the best option so far and also no longer even maintained.

> We are open for PR and will try to maintain existing functionality for the new Atom versions.

@ivankravets None of this seems even close to reality, PR's are left without review and hanging for months and current functionality is clearly going flaky with newer atom versions.

PR welcome yea, more like fork welcome.

`</endsadstateofaffairsrant>`

**Comment by Fred-Barclay** [comment]
Hi everyone,
I'm still actively maintaining my fork as best as I can, and looking for volunteers to help. With @ivankravets 's approval, this can be the spiritual successor to platformio-terminal.
https://github.com/Fred-Barclay/Termination/issues/75
Cheers!

**Comment by the-j0k3r** [comment]
@Fred-Barclay you should port many things from here to there.

**Comment by ivankravets** [comment]
> Plus, I'm not a coffeescript hacker, and for the forseeable future, I can't be.

How do you plan to maintain it? We don't have the useful PRs to this repository, see https://github.com/platformio/platformio-atom-ide-terminal/pulls.

If you plan that someone fixes issues and you merge PRs, it will not work. 

We need strong code review before merging something new. I'm opened for PR and can review them.

**Comment by the-j0k3r** [comment]
>We don't have the useful PRs to this repository, see https://github.com/platformio/platformio-atom-ide-terminal/pulls.

@ivankravets You have two bug fixes gathering cobwebs, is that not useful?

Slightly unfair comment there.

>We need strong code review before merging something new. I'm opened for PR and can review them.

Really, have you reviewed the open PR's? The bug fixes at least? Nope https://github.com/platformio/platformio-atom-ide-terminal/pull/525 not reviewed, fixes stuff and its there waiting for?

What about the other PRs? If you arent going to merge them new features close them.

IDK, I appreciate the existence o PIO but making claims is nice when backed by actionable verifiable info. Sorry to say Not meant to offend.

**Comment by Fred-Barclay** [comment]
@ivankravets good question, and I don't know for certain. Over time I would like to find collaborators who are dedicated, and then giving them full commit access so it becomes less my project and more a community-backed thing. But that's definitely not something I can count on. Possibly termination will end up the same way, maintenance but not actively developed.

Strangely enough, I've been mulling over seeing if I could open a few PRs here to allow your project to (optionally) look more like the old terminal-plus, and then closing up shop. I'm not critizing your decision to quit actively developing this, but I wouldn't want to do that without active development (instead of just merging PRs).

**Comment by the-j0k3r** [comment]
> to (optionally) look more like the old terminal-plus,

Optionally, phew OK, I like PIO how it looks and how it integrates with atom, something your project and terminal-plus was meant to integrate with very earlier version of atom and look out of place now, sorry to say.

I can tell you from experience that maintaining a project usable as a non coder is very time intensive to look ACTIVELY for developers who are willing at least to make a fix every so often. Otherwise its just just another dead fork.

Perhaps you can try talking to the people who made PR's here. But that leaves tons of code to handle from your side.

>Strangely enough, I've been mulling over seeing if I could open a few PRs here

Waste of time, your better to reverse the flow, take code from here since MIT lic what else do you need?

**Comment by Fred-Barclay** [comment]
> terminal-plus was meant to integrate with very earlier version of atom and look out of place now, sorry to say.

Haha, no worries. I didn't like PIO terminal as much when running in ordinary Atom (no offence @ivankravets ) so it looks more like terminal-plus. It can be made to look like PIO terminal though with the terminal icons and etc all on the left side by un-ticking the "Clone Terminal-Plus" box:
![image](https://user-images.githubusercontent.com/11165995/41502835-9d775230-71b2-11e8-9ea0-55e0e5daeefa.png)

EDIT: regarding your other points.
I'm not exactly a non-coder :) actually I work in a job that requires coding most days, but I'm a python and C guy. 
Termination isn't far behind PIO as far as I know. We didn't implement their API of several months ago, but that was a conscious choice and one I'm willing to reconsider. Other than that, I believe we have the same features. Definitely the MIT helps here. :grin:

**Comment by ivankravets** [comment]
Thank you so much for all contributions! v2.8.2 is out! 👍 

- https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.8.2

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 these type issue all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
