### ISSUE TITLE
ON STAT UP ATOM Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by kavinho** [platformio/platformio-atom-ide-terminal#562]
platformio-ide-terminal 2.7.0

pty.js@0.3.0 – Cannot find module '/Users/XXX/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin/darwin/x64_m57/pty.node'

ATOM version : 1.28.0 x64
OSX High Sierra / 10.13.2

**Comment by the-j0k3r** [comment]
> platformio-ide-terminal 2.7.0

You mean 2.8.3, right?

**Comment by KB7GP** [comment]
Is this directed to me regarding the window/pane position of ide-terminal (ver 2.8.3) within atom?
DaveR

**Comment by the-j0k3r** [comment]
> Is this directed to me regarding the window/pane position of ide-terminal (ver 2.8.3) within atom? DaveR

I would have thought if there is something to ask/comment or help to offer or anything at all, (I cant speak for anyone else) but my replies will be to the concerning ticket directly,

**Comment by KB7GP** [comment]
My original issue was 559 now closed as the updated terminal installed and runs fine.
I then later opened 560 which I just closed since it appeared to me, no one knew what I was talking about, or knew how to “fix” it or just didn’t care. I did not receive any suggestions or recommendations that may have corrected the issue. Still looking however.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
