### ISSUE TITLE
Terminal shows it is using the chosen python environment, though it is not

### ISSUE THREAD

**Issue by mike239x** [platformio/platformio-atom-ide-terminal#568]
I am using conda, in my `.bashrc` file I got the line 
`source activate p3`, which should activate the environment called "p3". If I normally open a terminal window I do get 

    (p3) mike239x@R2D2:~$ which python
    /home/mike239x/anaconda3/envs/p3/bin/python

as expected. Now I go to atom, open terminal window from PlatformIO, type the same thing, get this:

    (p3) mike239x@R2D2:~$ which python
    /home/mike239x/anaconda3/bin/python

So it shows that the "p3" environment is in use, though it is not. The simple check proved my theory:

    (p3) mike239x@R2D2:~$ source deactivate
    mike239x@R2D2:~$ source activate p3
    (p3) mike239x@R2D2:~$ which python
    /home/mike239x/anaconda3/envs/p3/bin/python

As you can see, now the source is the right one.

I consider this a bug, though I am not sure.

**Comment by mike239x** [comment]
Some extra details: 
ubuntu 18.04
conda 4.5.4
atom 1.28.1 x64
platformio-ide-terminal 2.8.3 -- installed via search of atom packages

**Comment by caopengbo** [comment]
Same issue, but why there is no any response? have you solved this problem?

**Comment by mike239x** [comment]
@caopengbo not really. I just added `source deactivate && source activate p3` in the auto run command field in the package settings, this helps. So, the problem is still there but I got a bandage.

**Comment by MinnML** [comment]
@mike239x, I have noticed exactly the same thing. Thanks for reporting this, because I could not load my python packages although I was thinking that I have them with the env activated. At least, I can use your workaround until this is fixed.

**Comment by the-j0k3r** [comment]
Please retest with platformio-ide-terminal 2.9.0

**Comment by crcdng** [comment]
Please reopen. Still broken in 2.9.1

**Comment by the-j0k3r** [comment]
@i3games actually this is for an outdated version of the plugin and thers no information provided by any person that would be relevant or actually helps triage issue.

if the issue is not related to flatpak installation of atom, then try to export your paths to `~/.bash_profile`

If that still doesn't fix it and you have no atom flatpack installation, **reopen a new issue filling in all provided template details plus also include as much extra information to help triage the issue fully.**

Thanks.
