### ISSUE TITLE
Selecting new theme doesn’t update the IDE

### ISSUE THREAD

**Issue by brandondurham** [platformio/platformio-atom-ide-terminal#578]
![Changing themes](http://cl.ly/tBM4/Screen%20Recording%202018-07-24%20at%2005.49%20PM.gif)

Should I be seeing the theme update real-time?

**Comment by the-j0k3r** [comment]
> Should I be seeing the theme update real-time?

You're supposed to close open terminals, apply new theme and reopen to see the new theme applied.

If you want the changes to occur live, you will need to submit a PR that makes this happen, thats because this project is not under active development anymore #543 
Else I dont think it will ever happen.

**Comment by the-j0k3r** [comment]
@ivankravets works as expected, please close.
