### ISSUE TITLE
Terminal double-spacing everything

### ISSUE THREAD

**Issue by will1054** [platformio/platformio-atom-ide-terminal#579]
After updating the package a couple weeks ago, my terminal has been double spacing everything. I've been using this package for a good year now and it was always fine before that. No idea what happened, but it gets quite annoying trying to read output with spacing like this:

![95e2f30cc640718d54d4f189748aebb8](https://user-images.githubusercontent.com/34065809/43259042-5655bd5c-90ab-11e8-9de9-445366a13165.png)

Any ideas?

**Comment by the-j0k3r** [comment]
Whats your atom version? Have you tried uninstalling and reinstalling the terminal?

**Comment by will1054** [comment]
Sorry, should have included that in OP. I'm version 1.27.2 and yes, I've re-installed platformio a couple of times to no avail.

**Comment by the-j0k3r** [comment]
update to atom 1.28.2 thats all I can suggest, I dont have or can duplicate that issue you describe.

If after you updated you still experience the issue, and have legacy console enabled as described in https://github.com/platformio/platformio-atom-ide-terminal/pull/575/files I suggest you try to disable it.

If that also fails, you should start  by disabling non core packages one by one testing in between and close reopen a terminal to see if issue persists, until the issue is gone, or you run out of extrenal extension to disable,

You can also try with a fresh atom configuration as descried in the debugging page for atom.

If the issue still persists after all that, youre SOL. As I said, I cant duplicate your issue.

**Comment by the-j0k3r** [comment]
AH yes, you can also downgrade or force install platformio-ide-terminal 2.8.2 IF AND ONLY you want to keep Atom 1.27.2

**Comment by will1054** [comment]
Upgrading Atom to 1.28.2, resetting it to factory defaults as described in the debugging docs, and re-installing packages did the trick. 

Thanks for the assistance!

**Comment by the-j0k3r** [comment]
YW. :smile:

**Comment by will1054** [comment]
Turns out the issue is being caused by the city-lights-UI theme - but even un-installing the theme doesn't fix it, I had uninstalled it and all other packages before going ahead with the factory reset. So when I was re-installing packages one-by-one and checking the terminal after each one, I found it was the culprit. And then of course I had to reset all over again.  😆

**Comment by the-j0k3r** [comment]
There is a PR adding support for that theme, I wonder if that fixes it.

see https://github.com/platformio/platformio-atom-ide-terminal/pull/572

@ivankravets PR's waiting for merge please review.
