### ISSUE TITLE
File drop in not working with Mojave

### ISSUE THREAD

**Issue by stephenwolfe1** [platformio/platformio-atom-ide-terminal#609]
After updating to MacOS Mojave, the drag and drop file path in terminal is not working. Atom and package are both updated to latest, Atom v1.31.1 and platform-ide-terminal v2.8.4.

**Comment by t0byman** [comment]
I have the same issue.

**Comment by t0byman** [comment]
Bump!

**Comment by the-j0k3r** [comment]
please install 2.9.0

**Comment by t0byman** [comment]
> please install 2.9.0

I did but it's still not working. I'm on Mojave 10.14.2 and Atom 1.34.0

**Comment by the-j0k3r** [comment]
Then aside from the usual debugging, like resetting atom to default and reinstalling platformio-ide-terminal, theres nothing else to do. Please read #543 the alternative is likely upgrading to xterm.js in this project, but it requires a bit of work in https://github.com/platformio/platformio-atom-ide-terminal/blob/master/lib/view.coffee

Given the project status its all up for grabs.

If you know any js, please consider contributing towards this at https://github.com/the-j0k3r/platformio-atom-ide-terminal/tree/switch-to-xterm-js

**Comment by the-j0k3r** [comment]
@stephenwolfe1 ping

Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 which since [f64888d](https://github.com/platformio/platformio-atom-ide-terminal/commit/f64888d6d134f7e06bbb13a762dfd45335e8a4ba) is using node-pty-prebuilt instead unmaintained and outdated pty.js. This is good news for stability and compatibility.

if issues persist, please open a new ticket with requested information.

Thx =)
