### ISSUE TITLE
square brackets macOS

### ISSUE THREAD

**Issue by abelfsousa** [platformio/platformio-atom-ide-terminal#619]
Hi guys,

I am having a problem with inserting square brakets in the atom command-line. Every time I press alt-8 "[" or alt-9 "]" (portuguese keyboard) I get this:

<img width="201" alt="screen shot 2018-10-23 at 20 17 27" src="https://user-images.githubusercontent.com/32486870/47418663-7db41e80-d772-11e8-951b-3aa4fa76f2a5.png">

This issue does not happen in a regular terminal window.

Does anyone know what might be the problem?

**Comment by the-j0k3r** [comment]
Try again with platformio-atom-ide-terminal 2.9.0

**Comment by the-j0k3r** [comment]
Also read https://github.com/platformio/platformio-atom-ide-terminal#support-for-special-keys

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 which since https://github.com/platformio/platformio-atom-ide-terminal/commit/f64888d6d134f7e06bbb13a762dfd45335e8a4ba is using node-pty-prebuilt instead unmaintained and outdated pty.js. This is good news for stability and compatibility.

if issues persist, please open a new ticket with requested information.

Thx =)
