### ISSUE TITLE
Install issues - "platform-atom-ide-terminal" does not work  after update 2.9.0

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#636]
After last update of "platform-atom-ide-terminal" to 2.9.0  the terminal opens but it doesn't give any output or accept any input, it looks that the terminal is frozen. Also the the Serial monitor does not give any output. No communication possible at all!

Windows 64-bit.
Atom 1.34.0
platformio ide 2.3.1

Uninstall of platform-atom-ide-terminal or/and platformio does not help.

Error:
connect ENOENT \\.\pipe\winpty-conin-6328-1-1d4b61f04a1ad23-cec26d243530c68bdbcd483718122ec7 Error: connect ENOENT \\.\pipe\winpty-conin-6328-1-1d4b61f04a1ad23-cec26d243530c68bdbcd483718122ec7
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

**Comment by the-j0k3r** [comment]
Its probably platformio ide 2.3.1, uninstall/reinstall that, It is working better than ever here.

**Comment by ghost** [comment]
It has nothing to do with platformio 2.3.1. I uninstalled and platformio 2.3.1 and platform-atom-ide-terminal" 2.9.0 and restarted Atom. Installed only platform-atom-ide-terminal" 2.9.0 and the terminal has exactly the same behavior. There is a windows with a blinking cursor but no input or output possible.

**Comment by ghost** [comment]
Sorry issue still exit, just hit the wrong button.

**Comment by dunkinman** [comment]
Yes!  No longer works!!!! 
Same config as above.
Windows 64-bit.  **  Windows 10 Pro
Atom 1.34.0
platformio ide 2.9.0

I was experiencing similar problems for the longest time whereby I had to constantly restart the terminal...in order to get it to come up....It seems as that issue was completely fixed about 3 months ago...Not sure what changed...But now this latest upgrade has thrown the terminal back into a tailspin for Windows 64-bit users.  I am running Windows 10 Pro...not sure if there's a difference as far as Atom and Windows 10 vs. Windows 10 Pro....perhaps that's part of the problem.

**Comment by dunkinman** [comment]
Just seemed to resolve by uninstalling platformio-terminal and plaformio-ide debugger and then reinstalling platformio-terminal.  But terminal color seems to be on the darker side of white almost gray.

**Comment by dunkinman** [comment]
Rebooted to ensure clean startup and now can't get it to come back up at all.  Dead in the water.  Not working at all.

**Comment by dunkinman** [comment]
Now after a series of opening and closing Atom and installing and reinstalling Platformio-IDE-Terminal.  It's up...at least for the time being.  Very unstable....

**Comment by dunkinman** [comment]
Is there some way to go back to previous version of platformio-IDE-terminal until QA issues with this release are fixed?  I am also willing to be a Beta tester for future releases to ensure problems like this are caught before the update is pushed out as well.  Please let me know how I can help in this regard and what I need to do in order to be a beta tester.

**Comment by the-j0k3r** [comment]
Yes you can install a previous version of any packages some how-tos online look at apm, but this project is not under active development see #543, so expecting any QA resolution to happen isnt realistic.

You should reset atom. and then reinstall platformio-ide-terminal.

Also you should know, this update changed the from pty.js to node-pty-prebuilt which is more stable and actively developed, and also some theme changes which may account for your experience. See https://github.com/platformio/platformio-atom-ide-terminal/commits/master

**Comment by dunkinman** [comment]
Hello!  And thank you for the quick response.  I’m a bit confused about your comments though.  You’re saying platformio isn’t under active development?  A new release was just pushed two days ago?  Are you suggesting I reset Atom and reinstall a prior version of platformio?  Finally I couldn’t quite understand your comments about pty-js.  Should I begin to explore terminal alternatives since I am using Windows 10 as my development platform?

**Comment by the-j0k3r** [comment]
Just about **bare minimum** is being done by the project owner to keep the project working with newer Atom versions, mainly merging PRs and making releases, No other owner fixes/feature are being added, the project owners have switched to vscode and no longer come here to take care of issues like before. Again this is explained in great detail in #543. Its not totally abandoned yet, hence the odd release, but the line is thin.

pty.js != node-pty-prebuilt, the former is unmaintained/abandoned while the latter is actively developed, more stable, and fixes many issues in this project. Clearly these fixes dont agree with your seemingly unstable environment, hence you report mixed results.

Given those results I suggested a sane course of action, reset atom to default, then reinstall platformio-ide-terminal, 2.9.0, if that doesnt work the install a previous version 2.8.4, The docs are somewhere related to apm on how to do this.

Good luck and bare in mind Im not part of the team/project, Im a user just like you.

**Comment by ghost** [comment]
Hi I didn't noticed "Platformio-atom-ide-term NO LONGER developed/maintained #543". Switched today to vscode and it works like a charm again. Close the case.

**Comment by dunkinman** [comment]
@the-j0k3r Thanks for the helpful information.  I didn't realize you were just a user as well.  Your posts have been helpful.  Is VSCODE a replacement for the terminal of platformio?

**Comment by dunkinman** [comment]
For anyone experiencing, this problem, I did some digging around and figured out how to restore back to the prior version.  First, I went to the core settings and unchecked the fourth box down for automatically update.  Then I uninstalled platformio-ide-terminal from the settings panel in Atom by clicking on Install and then finding platformio-ide-terminal and clicking on the uninstall button.  Then I went to the Windows terminal and I typed in apm install platformio-ide-terminal@2.8.4  (Make sure you're in your project directory...I'm using a VirtualEnv ) Once the install was done I then went out to the Atom repository and downloaded version 1.3.3.1 and clicked on it to install version 1.3.3.1.  After ensuring I was running 1.3.3.1 in and making sure that I was running platformio-ide-terminal 2.8.4 I verified all is well and back to normal.  As this thread and others have indicated it looks like platformio-ide-terminal is no longer supported...generally.  Another alternative is to use the Windows native terminal as well, but as most who have gotten comfortable with the platformio-ide-terminal know it's just a little more convenient to run the terminal in the editor screen.  Hope this helps anyone else who has been struggling with this issue since the platformio-ide-terminal upgrade to 2.9.0.

**Comment by the-j0k3r** [comment]
@dunkinman your unique environment may be the actual cause, usually the culprit is something you install and straight away you notice issues, like you mentions on another thread I also replied to.

Like I said, platformio-ide-terminal has never worked more smoothly in a very long time and when theres newer prebuilt modules, it will be even better.

**Comment by dunkinman** [comment]
@the-j0k3r What is it that makes my environment unique in your estimation?  My OS?  I know you referred to that theory in another string, but I'm not quite sure what you're referencing that would make my environment unique.  What OS are you running?  This installation works perfectly in the combination I outlined above.  It's moving to the newest release that is giving me grief.

**Comment by the-j0k3r** [comment]
@dunkinman I simply meant that your issue is very likely caused by installing external software, you have had instability and issues that cant be replicated because of this type situation in other reports, so its not surprising nothing fixes your issues.

Best advice I can give to you, is start with a fresh OS in a virtualmachine then add Atom + Platformio-ide-terminal.

**Comment by dunkinman** [comment]
@the-j0k3r What OS are you running?  Do you run Windows10 Pro?  I suspect that might be the issue...I don't have any special software this is a new laptop...and the version I pointed out works flawlessly...I'm not sure why you think it's an issue solely with me.  Others have reported issues as well.

**Comment by the-j0k3r** [comment]
Im running Win 10 pro 1803.

Your posts indicate great instability and random behaviors, anyone who reports this has some issues with their install, it also doesnt take any special software to conflict with others already installed packages.

Something is clearly going on more out of the ordinary with your install, again this is what your posts here and other tickets indicate. What others say "me too" is neither here nor there, because others also have no issues like this or other severe problems.

You could try disabling GPU usage in Atom and the virtualbox thing.

Failing that, idk.

**Comment by dunkinman** [comment]
@the-j0k3r You don't run a virtualenv?  I am also using running django.  Are you?  What is GPU?

**Comment by the-j0k3r** [comment]
no django and its Nvidia or virtualbox svga both work.

**Comment by dunkinman** [comment]
GPU is Nvidia?  I am running 1803 as well....Is Nvdia the processor you are running?  I am running Intel...64 bit....Are you running 64 bit as well?  I've got a Dell Inspiron 7773 laptop...

**Comment by the-j0k3r** [comment]
Nividia 1080ti/1060 + intel i7-7700K 64bit or virtuabox svga, same CPU.

**Comment by dunkinman** [comment]
@the-j0k3r ...you had suggested that I retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js...is there anything I need to change as it relates to the outdated pty.js?  Or just upgrade platformio-atom-ide-terminal and try again?  Last time I tried this is when I ran into issues.  Is there something additional I need to do other than just upgrading the terminal?

**Comment by the-j0k3r** [comment]
I dont think you should need anything else, but if you have python installed I think its wise to keep it at version 2.7.

If you still experience any issues please re-open a new ticket.

**Comment by dunkinman** [comment]
@the-j0k3r Perhaps that's my issue...I'm running Python 3.6 on my machine.  Could that be causing my issues?

**Comment by the-j0k3r** [comment]
Could be, but you can have several versions of python installed also, 3.6 for your stuff and 2.7 because  some prebuilt installer dependency doesnt support higher.

**Comment by mikimar** [comment]
Hi guys,

I was trying to install **platformio-ide-terminal 2.9.1** on **Atom 1.36.0**

but after about 2 minutes of installing all i get is :-  Installing “platformio-ide-terminal@2.9.1” failed.Show output…

- I have tried unchecking my proxy settings
- I have tried installing "npm install" package first

- I am using a windows 7  x64 system 

********** I get the error log below **************

Installing “platformio-ide-terminal@2.9.1” failed.Hide output…

> node-pty-prebuilt@0.7.6 install C:\Users\MIKIMA~1\AppData\Local\Temp\apm-install-dir-119325-2192-1bk1vbw.3i2t\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js


C:\Users\MIKIMA~1\AppData\Local\Temp\apm-install-dir-119325-2192-1bk1vbw.3i2t\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false ) 

prebuild-install WARN install unexpected end of file
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\mikimaraki\\AppData\\Local\\atom\\app-1.36.0\\resources\\app\\apm\\bin\\node.exe',
gyp verb cli   'C:\\Users\\mikimaraki\\AppData\\Local\\atom\\app-1.36.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--build_v8_with_gn=false' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\mikimaraki\AppData\Local\Programs\Python\Python37-32\python.EXE
gyp verb check python version `C:\Users\mikimaraki\AppData\Local\Programs\Python\Python37-32\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.7.3\r\n"
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\mikimaraki\AppData\Local\Programs\Python\Python37-32\python.EXE" is v3.7.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\mikimaraki\AppData\Local\atom\app-1.36.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\mikimaraki\\AppData\\Local\\atom\\app-1.36.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\mikimaraki\\AppData\\Local\\atom\\app-1.36.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\MIKIMA~1\AppData\Local\Temp\apm-install-dir-119325-2192-1bk1vbw.3i2t\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\MIKIMA~1\AppData\Local\Temp\apm-install-dir-119325-2192-1bk1vbw.3i2t\package.json'
npm WARN apm-install-dir-119325-2192-1bk1vbw.3i2t No description
npm WARN apm-install-dir-119325-2192-1bk1vbw.3i2t No repository field.
npm WARN apm-install-dir-119325-2192-1bk1vbw.3i2t No README data
npm WARN apm-install-dir-119325-2192-1bk1vbw.3i2t No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mikimaraki\.atom\.apm\_logs\2019-04-25T17_38_29_623Z-debug.log

**Comment by the-j0k3r** [comment]
@mikimar Thank you for reaching out with that issue report.

Please see this issue https://github.com/platformio/platformio-atom-ide-terminal/issues/637 which is same issue as yours.

Unfortunately thers nothing to be done, this issue should be reported to apm.

Most relevant part...

```
gyp ERR! stack Error: Python executable "C:\Users\mikimaraki\AppData\Local\Programs\Python\Python37-32\python.EXE" is v3.7.3, which is not supported by gyp.
```

**Comment by the-j0k3r** [comment]
# Reminder: 

Any installation issues [are to and should be reported to apm issue tracker](https://github.com/atom/apm/issues/new) **platformio-ide-terminal** cannot control **apm** which **is responsible for installs of all atom plugins and their dependencies** anyway, so **thanks in advance for your understanding in these matters**.
