### ISSUE TITLE
Terminal not showing anything after updating!!

### ISSUE THREAD

**Issue by jiveshs98** [platformio/platformio-atom-ide-terminal#638]
![issue](https://user-images.githubusercontent.com/29351433/51796025-3fffdf80-2212-11e9-8869-ebf865d8c271.JPG)

**Comment by the-j0k3r** [comment]
@ivankravets pls close.

**Comment by jiveshs98** [comment]
Could you please tell me what I should do to get it working properly?

**Comment by the-j0k3r** [comment]
Read https://github.com/platformio/platformio-atom-ide-terminal/issues/637#issuecomment-457905921

Also when opening a report, you should provide actual usable info for anyone to provide any kind of specific help, a screenshots are great along with proper info, not so great by themselves.

Output of:

`$> atom --version`
`$> apm --version`

Your OS name and version.
Screenshots
Post Any errors

Actual description of the issue.

Any less, is hindering.

**Comment by dunkinman** [comment]
For anyone experiencing, this problem, I did some digging around and figured out how to restore back to the prior version. First, I went to the core settings and unchecked the fourth box down for automatically update. Then I uninstalled platformio-ide-terminal from the settings panel in Atom by clicking on Install and then finding platformio-ide-terminal and clicking on the uninstall button. Then I went to the Windows terminal and I typed in apm install platformio-ide-terminal@2.8.4 (Make sure you're in your project directory...I'm using a VirtualEnv ) Once the install was done I then went out to the Atom repository and downloaded version 1.3.3.1 and clicked on it to install version 1.3.3.1. After ensuring I was running 1.3.3.1 in and making sure that I was running platformio-ide-terminal 2.8.4 I verified all is well and back to normal. As this thread and others have indicated it looks like platformio-ide-terminal is no longer supported...generally. Another alternative is to use the Windows native terminal as well, but as most who have gotten comfortable with the platformio-ide-terminal know it's just a little more convenient to run the terminal in the editor screen. Hope this helps anyone else who has been struggling with this issue since the platformio-ide-terminal upgrade to 2.9.0.
