### ISSUE TITLE
Not working with Atom 1.34.0 x64

### ISSUE THREAD

**Issue by nsingh415** [platformio/platformio-atom-ide-terminal#643]
Hi,

The terminal is not launching after an upgrade to ver. 2.9.0.

Please advise.

**Comment by TecMunky** [comment]
It is not working for me either on Windows 7.  
But it is working on Manjaro Linux.
Both operating systems have Atom 1.34.0 x64 version and ver. 2.9.0 of this package.

NB: I just recently installed this package - never used it with any previous versions of Atom

The error on Windows says "Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of atom."

Then for the module - "Rebuild Failed" with the following output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | win32 | x64
gyp http GET https://atom.io/download/electron/v2.0.16/iojs-v2.0.16.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\USER\\AppData\\Local\\atom\\app-1.34.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\USER\\AppData\\Local\\atom\\app-1.34.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=2.0.16" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\USER\.atom
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by the-j0k3r** [comment]
Please uninstall and reinstall platformio-ide-terminal via apm, if issue persists please reopen a new ticket with required information as these reports as above are not helpful.

Thx.

**Comment by TecMunky** [comment]
What information do you need to figure out the problem?

I cannot uninstall and reinstall via apm - because I cannot access the plugin database from my windows machine.  What I have been doing is installing plugins on my Linux machine, and transferring the plugins to my windows machine.  Every other plugin I transferred this way works perfectly.

**Comment by the-j0k3r** [comment]
> What information do you need to figure out the problem?

Not sure but https://github.com/platformio/platformio-atom-ide-terminal/blob/master/.github/ISSUE_TEMPLATE.md is a good start.

also see below.

> I cannot uninstall and reinstall via apm - because I cannot access the plugin database from my windows machine. What I have been doing is installing plugins on my Linux machine, and transferring the plugins to my windows machine. Every other plugin I transferred this way works perfectly.

Ah you see, this information is crucial but ommited until now., That solution is really not ideal, node-pty-prebuilt is packed for all OS specifically, so your particular workaround is probably breaking something as not everything will work as you describe, from expereince Linux/Windows do things in own way and are not necessarily interchangeable.

Your rebuilds fails and its indications are that its having communication issues.

Try to fix your windows box else cant really try to support these creative fixes.

**Comment by TecMunky** [comment]
I can't "fix my windows box" because the reason I can't download plugins is because it's behind a corporate firewall.

**Comment by TecMunky** [comment]
My original question remains.
What other information do you need?

**Comment by TecMunky** [comment]
My understanding is that the plugins themselves are not OS dependent.  Is this incorrect?

**Comment by the-j0k3r** [comment]
Yes but they are built specifically for each OS, platformio-ide-terminal uses now node-pty-prebuilt which has specific winpty executables for Windows, Linux, Darwin these are PREBUILT, so depending on which OS you are I imagine the correct ones are used, which with your creative "FIX" I cant tell for sure whats going on.

Best thing would be for someone to pack their working install and you use that, though this is as practical as your solution.

@ivankravets what do you think about the follwoing statement and do you have any advice?

>I cannot uninstall and reinstall via apm - because I cannot access the plugin database from my windows machine. What I have been doing is installing plugins on my Linux machine, and transferring the plugins to my windows machine. Every other plugin I transferred this way works perfectly.

**Comment by TecMunky** [comment]
So that means I need to download the version specifically for windows, on a computer that is not behind a corporate firewall.  How do I do that?  If I can independently download the plugin from a website, that would solve my issue because I could do that from the windows machine.  (assuming this is the correct solution, anyway).

**Comment by the-j0k3r** [comment]
From a virtual machine for instance on your Linux machine?
