### ISSUE TITLE
Issue with opening a new terminal

### ISSUE THREAD

**Issue by gowthambharadwaj** [platformio/platformio-atom-ide-terminal#659]
I cannot use the terminal to run my node js code.

**Comment by the-j0k3r** [comment]
Thank you for reaching out with this bug report.

You are getting this reply because the issue template was not filled in its entirety, overwritten,  or some portions were partially left out.

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

Tickets without this information may be closed and labeled invalid at our discretion.

Thank you for your understanding.

**Comment by mkismy** [comment]
Not sure if my issue is the same with @gowthambharadwaj, but `cmd-shift-t` no longer opens new terminal so now I have to open it by selecting from the menu bar.

![image](https://user-images.githubusercontent.com/8445575/53137786-6de50380-35c7-11e9-8680-0f9c32963b75.png)

**Comment by the-j0k3r** [comment]
@mkismy see https://github.com/platformio/platformio-atom-ide-terminal/commit/cb12f3127edb8364add8e53fe041aac5d28670fa
