### ISSUE TITLE
some platformio-atom-ide-terminal does not work

### ISSUE THREAD

**Issue by titocarmelo** [platformio/platformio-atom-ide-terminal#662]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment]
Thank you for reaching out with this bug report.

You are getting this reply because the issue template was not filled in its entirety, overwritten,  or some portions were partially left out.

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

Tickets without this information may be closed and labeled invalid at our discretion.

Thank you for your understanding.

**Comment by qeithva** [comment]
Got same issue: blinking cursor while opening terminal

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

Tried many things: uninstall atom all packages, etc reinstall all many times
but nothing helps 

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 3.5.2
git 2.16.2.windows.1
visual studio

**Comment by qeithva** [comment]
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 3.5.2
git 2.16.2.windows.1
visual studio

**Comment by the-j0k3r** [comment]
@qeithva Not same issue, At this time we dont know what issue is even the op didnt explain anything or fill in required issue template, Please open a new ticket and fill in all template details and add screenhsots or gif captures.

Also please follow https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

Then reinstall platformio-ide-terminal 2.9.1 via apm in a terminal.

This ticket though is invalid as we cant guess what OP meant and we have no information whatsoever..

@titocarmelo reopen a new ticket and this time dont ignore the issue template.
