### ISSUE TITLE
macOS: bug with @

### ISSUE THREAD

**Issue by dark-kitt** [platformio/platformio-atom-ide-terminal#674]
Hey guys,

It's not possible to write an @ (E.g. ssh user =>@<= ip).
Copy and paste works.

Versions:
plat ide terminal => 2.9.1
atom => 1.34.0 x64
mac osx => 10.13.6

keys => alt (option) + L

Cheers

**Comment by the-j0k3r** [comment]
Thank you for reaching out with this bug report.

You are getting this reply because the issue template was not filled in its entirety, overwritten,  or some portions were partially left out.

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

Tickets without this information may be closed and labeled invalid at our discretion.

Thank you for your understanding.

**Comment by the-j0k3r** [comment]
Closing as invalid for lack of response and template information not being provided.
However a quick test in macOS Mojave 10.14.2 reveals there is no issue whatsoever here with this (given there is not enough info to duplicate exactly what is reported.).

![macOSssh](https://user-images.githubusercontent.com/31389848/54735396-4ec99980-4ba6-11e9-94eb-ced001f4e33b.gif)

If the whole template is filled in in a nearby future, the ticket can be reopened, though I cant duplicate the issue reported as @ works just fine. I suggest you look at your configuration

Thank you for your understanding.
