### ISSUE TITLE
CTRL + C not working

### ISSUE THREAD

**Issue by i1Fury** [platformio/platformio-atom-ide-terminal#675]
ALL THAT IS NECESSARY:

### Steps to reproduce
1. Run python script
2. Hit CTRL + C to stop

**Expected behavior:** 
The python script stops

**Actual behavior:** 
The python script doesn't stop

**Reproduces how often:** 
85%

OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment]
Thank you for reaching out with this bug report.

You are getting this reply because the issue template was not filled in its entirety, overwritten,  or some portions were partially left out.

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

Tickets without this information may be closed and labeled invalid at our discretion.

Thank you for your understanding.

**Comment by the-j0k3r** [comment]
Turns out this is a git issue See https://github.com/git-for-windows/git/issues/1470

**Comment by the-j0k3r** [comment]
I closed this for 2 reasons, 

1) Not enough info provided to duplicate despite @UGEYT insisting there no other requirements needed.
2) Since cant duplicate and after waiting nearly a month for a reply, its plain to see, its not possible to help those who cant/wont help other help them.

I usually lock threads once closed, but Ill leave this open in case @UGEYT provides step by step instructions The OS type, etc that was missing and provides an example script or anything hat will allow someone to replicate this.
Also a reproduction percentage of 85% tells me its likely the script wont be interrupted past some point, which is likely..

Once that is done Ill reopen this. =)

Also read #543 and #426 which the latter would improve compatibility and robustness.
