### ISSUE TITLE
Theme error

### ISSUE THREAD

**Issue by svliantiss** [platformio/platformio-atom-ide-terminal#677]
When creating a new theme it overwrites all other themes, until reinstallation or deletion of the theme file.

**Comment by the-j0k3r** [comment]
Thank you for reaching out with this bug report.

You are getting this reply because the issue template was not filled in its entirety, overwritten,  or some portions were partially left out.

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

Tickets without this information may be closed and labeled invalid at our discretion.

Thank you for your understanding.

**Comment by svliantiss** [comment]
I've already reinstalled the package so the error is gone, but it might be great to set it up so this doesn't happen more often, by elaborating/informing more in the guide.

**Comment by the-j0k3r** [comment]
@svliantiss I dont even have a slightest idea what you actually did or what issue actually was, but all indications point to a local issue with your install. Why, no idea, Not enough information was provided to get further than a wild guess.

I never had such an issue, and creating themes here doesn't break anything.

Im glad its sorted itself out. =)
