### ISSUE TITLE
How to connect ssh throught Windows 10 ?

### ISSUE THREAD

**Issue by webmasterpf** [platformio/platformio-atom-ide-terminal#678]
Hi,

I'm able to connect my Linux server via SSH connection from Windows client machine into Atom.
All work fine with Putty or MRemote and netbeans too.

But if I lauch a terminal into Atom woth platformio, and cmde.exe I get this:

```
C:\Users\XXX>ssh XX@10.XXX.XX.XX
'ssh' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
```

With Powershell, same issue, despite installing Posh-SSH.
If I launch putty with platformio, terminal is outside Atom, it's not the desired behaviour. Remote-ssh does the same.

So how can I get SSH connection into Atom ?

Thanks

**Comment by the-j0k3r** [comment]
Hello and thanks for reaching out with this query.

Just to clarify, if you run powershell outside Atom + POSH-SSH it still errors out?

Whats your ExecutionPolicy set to? Try setting it to unrestricted `Set-ExecutionPolicy Unrestricted`
Also may want to install https://github.com/sshnet/SSH.NET, which is what posh-ssh uses.

Regards.

**Comment by webmasterpf** [comment]
With powershell outside or inside Atom I get:
```
ssh : Le terme «ssh» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme
exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct
et réessayez.
Au caractère Ligne:1 : 1
+ ssh XX@xx.xx.xx.xx
+ ~~~
    + CategoryInfo          : ObjectNotFound: (ssh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
For ExecutionPolicy, I don't know where I can find this ? I will install SSH.NET to see if things change.

**Comment by the-j0k3r** [comment]
Because this is happening to you outside Platform-ide-Terminal we can exclude this project as the problem. =)

Regarding the execution policy see:  https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-executionpolicy?view=powershell-6 it will show you how to query/set execution policies (though I have provided you with the [command for Powershell on my post above](https://github.com/platformio/platformio-atom-ide-terminal/issues/678#issuecomment-480221674))

I suggest you query your ExecutionPolicy state before setting a new execution policy, Some Powershell modules like posh-SSH **will very likely require unrestricted permissions** I suspect this is true as Im not familiar with that project,

if you dont know what ExecutionPolicy level poshSSH requires, I suggest you ask the developers for posh-SSH. You can also ask them if it requires SSH.NET to be 100% sure. And in turn that also may have its own requirements, again same thing, ask the developers.

I hope thats of help, I cant take you any further.

Good luck =)

Personally I only run modules with unrestricted execution policies only when I absolutely trust the source =).

EDIT: seems your problem is with posh-SSH, please read the https://github.com/darkoperator/Posh-SSH/issues?q=is%3Aissue+execution+policy+is%3Aclosed, Also open an issue with tehir project, seems you dont actually have installed posh-SSH properly.

**Comment by webmasterpf** [comment]
ok, I just open an issue on their project.
https://github.com/darkoperator/Posh-SSH/issues/263

Will see.
