### ISSUE TITLE
Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by swapnilkawale** [platformio/platformio-atom-ide-terminal#689]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro N
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.9.1

### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At C:\Users\swapn\.atom\packages\platformio-ide-terminal\lib\view.coffee:646

TypeError: Cannot read property 'element' of undefined
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.adjustHeight (/packages/platformio-ide-terminal/lib/view.coffee:646:30)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.maximize (/packages/platformio-ide-terminal/lib/view.coffee:371:14)
    at /packages/platformio-ide-terminal/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -4:09.4.0 core:page-down (div.package-detail)
```

### Non-Core Packages

```
autocomplete-python 1.14.0 
kite 0.161.0 
platformio-ide-terminal 2.9.1 
```

**Comment by the-j0k3r** [comment]
Hello @swapnilkawale and thank you for reaching out with this issue report.

This is like a garbage error, not helpful to triage and who knows whats triggering it.

I would disable any 3rd party antivirus softwares and actually fill in our issue template which you have overwritten with some random template which is unrelated to our issue template.

In any case I think this is caused by 3rd party softwares and even if it isnt, the error as said above is impossible to pin to something internal.

**Comment by the-j0k3r** [comment]
Try with Atom 1.40.1 and platformio-ide-terminal 2.9.4, if error repeats fill in all template details and report a new issue.

Thanks for understanding.
