### ISSUE TITLE
using shift + cmd + / for comment files *.html.eex in Phoenix Framework error

### ISSUE THREAD

**Issue by romenigld** [platformio/platformio-atom-ide-terminal#696]
### Description
I'm using the command `shift + cmd + /` for comment in `*.html.eex` files  with the  Phoenix Framework and the Atom app puts comments in those file like this:
`<!-- comments  -->`
but this comments don't works on those file. For example I put an Issue [here](https://github.com/phoenixframework/phoenix/issues/3423)
And this was the problem.
So the correct way for comment on those files is like this:
```
 <%#= for key <- connection_keys(@conn) do %>
    <%#= render("key.html", key: key) %>
  <%# end %> 
```
> atom --version
Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

```
```
> apm --version
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.37.0
python 2.7.15
git 2.20.1

```
OS name and version: Mac OS Mojave 10.14.5

**Comment by the-j0k3r** [comment]
Hello and thank you for reaching out with this issue report.

Platformio-ide-terminal doesnt insert anything or format anything at all that you dont insert yourself, so I fail to see how this applies to this specific project. **You are probably using some syntax autocompleter that doesnt support your phoenix framework,** This project literally does not have anything to modify any such areas.

**Also you failed to properly fill in the issue template**, which mean the lack of actionable information that would for instance enable me to duplicate the issue in my own setup, is simply not there, so theres nothing I can do here further to try help you.

Im slightly curious how you reached the conclusion that **platformio-ide-terminal** is the app causing the issue since its a pseudo terminal,  I recommend you actually report the issue to the correct project, and its not this one. For Atom bugs see https://github.com/atom/atom/issues/new/choose

If you properly fill in all issue template fileds providing step by step instructions and screenshots + a list of installed 3rd party plugins I may take a look at it again, but for now, theres nothing else to do here.

Thank you for understanding.

**Comment by romenigld** [comment]
Hello @the-j0k3r,
sorry if here it isn't the correct place for post here.
I was seeking something to change how the comments on those type of files and I see something with commands and I create this issue.
And thank you for reply and post the correct place for post this issues..

**Comment by the-j0k3r** [comment]
@romenigld you need to find the atom extension that is causing this, its not Atom/this repo or phoenix repo.

My guess is you are using some HTML beautifier or something of the sort and that is likely the extension causing this. It shouldnt be hard to find but you need to provide that information and you only provide the issue.

Good luck in finding the project causing this.
