### ISSUE TITLE
None of your packages contain incompatible native modules.

### ISSUE THREAD

**Issue by Alreadywinner** [platformio/platformio-atom-ide-terminal#719]
Whenever I am trying to download the terminal only one bug is again and again coming as the above stated please help me !

**Comment by the-j0k3r** [comment]
Thank you for bringing this issue to our attention.

You are getting this reply because the issue template was not filled in its entirety, overwritten,  or some portions were partially left out.

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md). Such as screenshots.

>Note: Tickets without this information may be closed and labeled invalid at our discretion.

On a second note this doesn't seem related to this project Perhaps Atom project wild guess based on the really small amount of actionable information provided) so, once you have provided the required information as above, Ill be happy to take another look at this again.

Thank you for your understanding.

**Comment by the-j0k3r** [comment]
ping

**Comment by the-j0k3r** [comment]
This happens when there was a successuf rebuild of a previous incompatible package, just close the tab.
