### ISSUE TITLE
can't install platformio ide terminal  (windows )

### ISSUE THREAD

**Issue by dznlv** [platformio/platformio-atom-ide-terminal#726]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

also apm not working in cmd

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment]
@dznlv thank you for reaching ou to use with this issue report.

Please do not ignore the issue template fields in future, this sort of disregard isnt helpful in any case, in this instance the issue is well know, and, many duplicates to #700 have been filed including yours.

There is a workaround, its been posted in this issue https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 < click that.

Thanks for your understanding.
