### ISSUE TITLE
Cant install it

### ISSUE THREAD

**Issue by pronatadatta** [platformio/platformio-atom-ide-terminal#741]
Installing “atom-ide-terminal@5.0.1” failed.Hide output…

> node-pty-prebuilt@0.7.6 install /private/var/folders/8t/y8tk432j69dbyww5y973dcph0000gn/T/apm-install-dir-119629-1298-1731ruv.vd5t/node_modules/atom-ide-terminal/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=darwin)
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd /private/var/folders/8t/y8tk432j69dbyww5y973dcph0000gn/T/apm-install-dir-119629-1298-1731ruv.vd5t/node_modules/atom-ide-terminal/node_modules/node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok

**Comment by the-j0k3r** [comment]
Thank you for reaching out to use with this issue report.

Please do not ignore the issue template fields in future, this sort of disregard isnt helpful in any case, in this instance the issue is well know, and, many duplicates to #700 have been filed including yours.

There is a workaround, its been posted in this issue https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 < click that.

There are other workarounds in thread, so reading and typing more than the minimum is necessary.

Thanks for your understanding.
