### ISSUE TITLE
package compatibility issue 

### ISSUE THREAD

**Issue by titanRoyal** [platformio/platformio-atom-ide-terminal#744]
i get a package compatibility warning about paltform ide terminal that it can not rebuild the package now i cant even intall the platform ide terminal

**Comment by Anjaan-g** [comment]
I am getting the same warning and now it's not running.

**Comment by the-j0k3r** [comment]
Thank you for reaching out to use with this issue report.

Please do not ignore the issue template fields in future, this sort of disregard isnt helpful in any case, in this instance the issue is well know, and, many duplicates to #700 have been filed including yours.

There is a workaround, its been posted in this issue https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 < click that.

There are other workarounds in thread, so reading and typing more than the minimum is necessary.

Thanks for your understanding.
