### ISSUE TITLE
Terminal is not start

### ISSUE THREAD

**Issue by uadminu** [platformio/platformio-atom-ide-terminal#761]
![IMG_0957](https://user-images.githubusercontent.com/16014818/62402331-8147c200-b59c-11e9-9b93-6665820341a9.jpeg)
I reinstall it but terminal not start:(

**Comment by the-j0k3r** [comment]
Thank you for reaching out to use with this issue report.

Please do not ignore the issue template fields in future, this sort of disregard isnt helpful in any case, in this instance the issue is know, and, #760 have been filed already before your issue..

There is a workaround (for Windows only), its been posted in this issue https://github.com/platformio/platformio-atom-ide-terminal/issues/760#issuecomment-517757440 < click that.

Thanks for your understanding.
