### ISSUE TITLE
Platformio-ide-terminal Installation Error

### ISSUE THREAD

**Issue by arlhs** [platformio/platformio-atom-ide-terminal#774]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```1.29.0
```
> apm --version

```1.19.0
OS name and version:
Platformio-ide-terminal version:
Windows 10 Home Basic

### Additional Information
<!-- Add any additional information like screenshots, gif captures,
configuration, data or other Atom package lists, that might be necessary to reproduce the issue. -->
![image](https://user-images.githubusercontent.com/19245260/63220558-e52ad700-c1a7-11e9-834c-147323c7f665.png)

[2019-08-18T00_00_13_165Z-debug.log](https://github.com/platformio/platformio-atom-ide-terminal/files/3512714/2019-08-18T00_00_13_165Z-debug.log)

**Comment by the-j0k3r** [comment]
Thank you for reaching out with this bug report.

You are getting this reply because the issue template was not filled in its entirety, overwritten,  or some portions were partially left out.

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

Tickets without this information may be closed and labeled invalid at our discretion.

Thank you for your understanding.
