### ISSUE TITLE
Installing 2.9.4 in Atom 1.40.1

### ISSUE THREAD

**Issue by JamoDevNich** [platformio/platformio-atom-ide-terminal#777]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Description

Terminal fails to install the latest version 2.9.4 from within Atom Editor on a system which has previously installed Terminal using APM outside the Atom Editor.

### Steps to reproduce

1. Launch Atom, head to Install
2. Search for PlatformIO Terminal and hit install
3. Install fails with this error:
![image demonstrating installation error](https://i.imgur.com/GLRivuI.png)

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version: Windows 10 x64 Professional
Platformio-ide-terminal version: 2.9.4

### How to fix this issue
1. When the error message pops up within Atom, copy the path highlighted in the picture above.
2. Paste it into your file explorer and navigate to the folder.
3. Delete the folder 'PlatformIO-IDE-Terminal'
4. Restart Atom and attempt re-installation (it may already show up as installed)

**Comment by the-j0k3r** [comment]
@JamoDevNich the issue was upstream with Atom 1.40.0 and apm, if you upgraded to 1.40.1 from 1.40.0 it may explain any problems getting there, but it works fine if you go from 1.39.1 to 1.40.1

See https://github.com/platformio/platformio-atom-ide-terminal/issues/770 and more specifically https://github.com/atom/atom/issues/19780 Which introduced the issue into Atom 1.40.0
