### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#781]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

installation failed

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 
I was installing the package. so I was expecting it to install ofcourse

**Actual behavior:** 
installation fails

**Reproduces how often:** 
100%

### Versions

```
> atom --version
the latest one
```
```
> apm --version
not sure
```
OS name and version: windows 10 64bit
Platformio-ide-terminal version:
whatever will be installed if it does
![Screenshot (21)](https://user-images.githubusercontent.com/28987008/64078420-181cb100-ccf8-11e9-944e-82499f3cbdcd.png)
![Screenshot (21)](https://user-images.githubusercontent.com/28987008/64078423-1eab2880-ccf8-11e9-949e-dc52e2d8778c.png)

**Comment by the-j0k3r** [comment]
> ```
> > atom --version
> the latest one
> ```
> 
> 
> ```
> > apm --version
> not sure
> ```

@NeeKay , youre suppose to type those commands (`atom --version` and `apm --version`) on a terminal and press enter, copy and paste the results here, As is those answers (not sure and the latest one are meaningless) and could lead a clew, since the error is also not clear,

Could you also copy and paste that log in the path the screenshots show here.

Will wait until these details are available,

Thanks.

**Comment by the-j0k3r** [comment]
@NeeKay you may want to try with python 2.7.15 x64 installed, if that doesnt work then report any instalation issues to apm https://github.com/atom/apm/issues/new?template=bug_report.md

apm is responsible for all plugin installations/uninstallations in Atom.

thanks for understanding
