### ISSUE TITLE
sudo apm install platformio-ide-terminal FAILED

### ISSUE THREAD

**Issue by yaolin902** [platformio/platformio-atom-ide-terminal#785]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Description

I can't install the plugin

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

```
> apm --version

```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python 2.7.16
git 2.20.1

OS name and version: xubuntu 19.04
Platformio-ide-terminal version: latest one?

### Additional Information

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /tmp/apm-install-dir-11986-12913-18tffj0.xpyw/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

sh: 1: prebuild-install: Permission denied
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-11986-12913-18tffj0.xpyw/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch/scripts/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11986-12913-18tffj0.xpyw/package.json'
npm WARN apm-install-dir-11986-12913-18tffj0.xpyw No description
npm WARN apm-install-dir-11986-12913-18tffj0.xpyw No repository field.
npm WARN apm-install-dir-11986-12913-18tffj0.xpyw No README data
npm WARN apm-install-dir-11986-12913-18tffj0.xpyw No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/y41/.atom/.apm/_logs/2019-09-06T22_25_04_772Z-debug.log

log: https://pastebin.com/mXyLrS9P

Have a good day!

**Comment by the-j0k3r** [comment]
HI @uygwfd254 for reporting this issue.

1st Im not sure you should be at all using sudo here, Atom should be installed into user folders, and second, its an apm issue. 

The error code 134 means node.js is likely running out of memory.

1st make sure youre not installing Atom via flatpack or snap or whatever, they are snadboxed and dont work well when installin. Then try again without sudo.

If the issue persists, open an issue with apm, https://github.com/atom/apm/issues/new/choose

As a reference it may actually be an issue with Atom and ubuntu 19.04 because of https://stackoverflow.com/questions/57618157/getting-a-nodejs-npm-error-installing-atoms-hydrogen-package-at-ubuntu is quite similar to your issue.

Thers literally nothing to do here in this project regarding the issue though as we have no control over Atom and APM

Have a good weekend.

**Comment by the-j0k3r** [comment]
Please report any installation issues to apm

https://github.com/atom/apm/issues/new?template=bug_report.md

Theres nothing to do here we have no control over instalation/uninstalation as that is handled by apm.

Also since there no further replies from you with new information I cant suggest anything else.

Closing issue as upstream/external issue for the reasons quoted re apm.

Thanks for understanding.
