### ISSUE TITLE
platformio-ide-terminal doest not work after upgrade when using Python 3

### ISSUE THREAD

**Issue by stuartsimpson** [platformio/platformio-atom-ide-terminal#787]
I have been struggling with this and found that the original issue had been closed and was restricted to contributors.  I have found that if you install Python 2.7 the issue is resolved and is the easiest solution to the issue of 2.9.x not working after upgrade.  Until this issue is resolved can you update Issue [Install issues - "platform-atom-ide-terminal" does not work after update 2.9.0 #636](https://github.com/platformio/platformio-atom-ide-terminal/issues/636) with this information.  It will save time for those trying to find an answer to there problem.

**Comment by the-j0k3r** [comment]
@stuartsimpson 

You may want to consider the follwoing:

node-pty-prebuilt-multiarch only uses node-gyp which requires python 2.7 as you have noted, [when in fact theres are no prebuilt binaries against the Atom electron version when you try to install platformio-ide-terminal.
This means that otherwise the python version is irrelevant.](https://github.com/oznu/node-pty-prebuilt-multiarch#how-it-works)

There have also been several issue lately with upstream bugs like https://github.com/atom/atom/issues/19780 and https://github.com/microsoft/node-pty/pull/339 both have been resolved in respective order by Atom 1.40.1 and https://github.com/oznu/node-pty-prebuilt-multiarch/pull/4

This mean that if you install Atom 1.40.1 and platformio-ide-terminal 2.9.4 There should be no issue, because we now support prebuilt binaries for electron 3.x, 4.x and 5.x in all supported OS's

If you have for instance and older version of Atom say 1.34.0 you have to use an older version of platformio-ide-terminal that ships 2.x electron prebuilt binaries, else you may encounter your issue, since our prebuilt binaries for current versions no longer support electron 2.x, only 3.x and up.

Of course since you have not provided any actionable information as required by the issue template, that I dont know your Atom version vs platformio-ide-terminal version you experience your issue, along with other required info you have omitted that in turn only leaves guessing from my part and any one looking to help you or share tips or something. Its not easy to try to guess what exact circumstances some issue is triggered.

Also regarding locked issues, they are locked in order to curb reports against fixed/external/outdated/duplicate or invalid reports, most of the cases have had newer developments that make some issue outdated, but if you do feel otherwise you can still link that issue on a new issue that you are trying to report. You also did not do this so Ive no reference to any possible actionable information.

If you do want to add any more information thats actionable so others can relate to your reports, please feel free to do so at any time, such as the full issue template details or links to some locked/other issue, screenshots logs etc.

But thanks for the heads up, I hope my reply has shed some new insights you may find useful and Ill be looking forward to clarify anything further if I can.

Regards.

**Comment by stuartsimpson** [comment]
Thank you for the response.  Sorry for not including the template information.  You will find all of that information listed below.  Based on what you have said above and the version I have listed below there may still be a bug in the installation.  When I ran into this issue I was running Atom 1.40.1 x64,  platformio-ide-terminal 2.9.4.  I tried to uninstall and reinstall the plugin without success.  Once I installed Python 2.7 the issue was resolved when using the standard method for installing Atom plugins.


- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Description
After upgrading to platformio-ide-terminal 2.9.4 the plugin stopped working and the icon for launching a terminal window was unavailable.

### Steps to reproduce

1. the issue became apparent right after upgrading platformio-ide-terminal and restarting Atom



**Expected behavior:** 
Plugin would be available to open windows Terminals from within Atom IDE.

**Actual behavior:** 
Plugin is not available.

**Reproduces how often:** 
was consistently all the time prior to installation of Python 2.7


### Versions


```
> atom --version

Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
```
> apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python 2.7.16
git 2.18.0.windows.1

visual studio 2015
```
OS name and version: Windows 10 Enterprise version 1703 OS Build 15063.1988
Platformio-ide-terminal version: 2.9.4


### Additional Information

**Comment by the-j0k3r** [comment]
Thats really odd and makes no sense given how it works especially in Atom 1.40.1 which fixed a known installation issue with apm.

Also it may be worth to you to report any installation issues to the Atom APM repo since that is what is responsible for all installs/uninstalls of all Atom plugins, so any bugs that may exist re installation are part of that. 

See https://github.com/atom/apm/issues and look for reports show same installation errors you experienced maybe https://github.com/atom/apm/issues/866 or another or something else.

Again, thanks for the heads up, Ill keep this in mind when other reports come in. Though Ill close the issue for now to avoid me too reports without any information I need to see where issue lies.

thanks for understanding.
