### ISSUE TITLE
Atom 1.32.2 and platformio-ide-terminal 2.9.4

### ISSUE THREAD

**Issue by maniac0s** [platformio/platformio-atom-ide-terminal#798]
Doesn't work.

All I get is a blank window with a blinking cursor without a prompt, that does nothing when I try to enter something.

Atom Version: 1.32.2

**Comment by the-j0k3r** [comment]
@maniac0s You have two options.

1) Upgrade to Atom production release 1.40.1 and use platformio-ide-terminal 2.9.4
2) Downgrade  platformio-ide-terminal to version 2.9.0

Atom 1.32.2 uses electron 2.x and current platformio-ide-terminal only supports electron 3.x, 4.x and 5.x, so upgrade Atom or downgrade platformio-ide-terminal are only options.

Also in future please do not ignore our issue template. providing that information is the minimum consideration you need to extend to whoever is donating their free time to help you.

**Comment by the-j0k3r** [comment]
@maniac0s You have two options.

1) Upgrade to Atom production release 1.40.1 and use platformio-ide-terminal 2.9.4
2) Keep Atom ancient version 1.32.2 and downgrade  platformio-ide-terminal to version 2.9.0

Atom 1.32.2 uses electron 2.x and current platformio-ide-terminal only supports electron 3.x, 4.x and 5.x, so upgrade Atom or downgrade platformio-ide-terminal are only options.

To downgrade platformio-ide-terminal do:

`apm uninstal platformio-ide-terminal`
`apm install platformio-ide-terminal@2.9.0`

In future when reporting issues to us, please do not ignore our issue template. providing that information is the minimum consideration you need to extend to whoever is donating their free time to help you. This project is community driven by other users and is what keeps it working/and with online support.

Thank you for your understanding.

**Comment by maniac0s** [comment]
Must be a Debian thing although I run Debian testing, I am not getting the latest package of Atom.

Alternatively Atom should only offer package versions applicable for it's currently installed version but that's an Atom issue in this case.

**Comment by the-j0k3r** [comment]
Well theres no way I know of to manage this with `apm` Atom package manager.

Atom electron version has been changing dramatically, for instance current Atom production 1.41.0 uses electron 4.2.7 and even though current platformio-ide-terminal 2.9.4 supports electron 3.x 4.x and 5.x thats not swapped automatically either. All we can do here is make sure our latest release supports the current Atom electron versions and the rest is taken as it comes.

That means that if you have Atom 1.40.1 with electron 3.x and platformio-ide-terminal 2.9.4 and then Atom upgrades to 1.41.0, you end up with a broken terminal because the node-pty-prebuilt-multiarch version installed supports electron  3.x when the new Atom needs 4.x..
Only way around it as is, its manual because apm and node-gyp are buggy and arent smart tools.

platformio-ide-terminal is in the middle, so invariably everyone thinks its an issue with our project and not external.

Nice eh?
