### ISSUE TITLE
Shortcuts with arrows don't work

### ISSUE THREAD

**Issue by Alex-Momotov** [platformio/platformio-atom-ide-terminal#804]
Hi,

I am trying to create shortcuts that move between terminal tabs ('platformio-ide-terminal:prev' and 'platformio-ide-terminal:next'). However, the shortcuts don't work if the desired key combination involves arrow keys. For example, the following doesn't work:
'.platform-darwin .platformio-ide-terminal .terminal':
     'cmd-alt-left': 'platformio-ide-terminal:prev'
     'cmd-alt-right': 'platformio-ide-terminal:next'

Atom: 1.41.0
OS: Mac Mojave

**Comment by the-j0k3r** [comment]
@Alex-Momotov its a limitation of term.js which is abandoned project on which platformio-ide-terminal currently depends, See #426 if interested. We would need to move to xterm which means updating to support the xterm.js API.

This project is fully community driven since https://github.com/platformio/platformio-atom-ide-terminal/issues/543 this means any support, fixes and additions are provided by the community.

If you can help out, It would be appreciated.

Please note this project is also superseded by https://github.com/bus-stop/terminus which is a fork where it is planned to [decaffeinate the project](https://github.com/bus-stop/terminus/commits/decaffeinated-terminus) so contributions are welcome.

Thanks for your understanding.

**Comment by the-j0k3r** [comment]
Also you dont need to create shortcuts for this, they already exist and work, granted not arrows but its better than nothing in the meanwhile

https://github.com/platformio/platformio-atom-ide-terminal/blob/f61084493ed48db11d2e54d39e01c1b88e693654/keymaps/platformio-ide-terminal.cson#L3-L4

**Comment by Alex-Momotov** [comment]
Thank you for such a detailed response, I really appreciate it. I am mainly a java and python dev, so not sure this can be much of help for the project. Yup, I'm aware of those shortcuts, just wanted to create a more natural experience since 'cmd-alt-left' and 'cmd-alt-right' is what most browsers use. Thanks for your help!

**Comment by the-j0k3r** [comment]
This is related to https://github.com/platformio/platformio-atom-ide-terminal/issues/807

So Ill mark it as duplicate, this issue is cross platform, but term.js or atom idk at this time.
