### ISSUE TITLE
Text getting cut off at bottom of screen div overlaps by 10px

### ISSUE THREAD

**Issue by asdf23** [platformio/platformio-atom-ide-terminal#809]
The .terminal div inside of .xterm is always 10px larger than .xterm itself. If I open the debugger I can reset the size and this resolves the issue. Resizing the display resets the .terminal div to be 10px larger again. 
This is noticeable when the contents of the terminal consume the entire height, when this occurs the last 1/2 of the text of the last line is cut off. 
Perhaps there are font calculations involved here but I believe it is safe to say that .terminal should never be larger than .xterm

**Comment by the-j0k3r** [comment]
Thank you for reaching out with this bug report.

You are getting this reply because the issue template was not filled in its entirety, overwritten,  or some portions were partially left out.

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

Tickets without this information may be closed and labeled invalid at our discretion.

Thank you for your understanding.
