### ISSUE TITLE
Installation of “platformio-ide-terminal@2.10.0” failed for Atom

### ISSUE THREAD

**Issue by fg1972** [platformio/platformio-atom-ide-terminal#839]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x ] I have not reset Atom to defaults prior to submitting report.
### Description
Installation of “platformio-ide-terminal@2.10.0” failed for Atom1.28.2 x64

### Steps to reproduce

1.Go to File --> Settings in Atom editor
2. Click on Install
3. Search for "Terminal"
4. Click on "Install" blue button under platformio-ide-terminal

**Expected behavior:** 
Install platformio-ide-terminal

**Actual behavior:** 
Gives error message after processing for a while

**Reproduces how often:** 
Tried thrice. Same result.

### Versions

```
> atom --version
1.45.0 x64
```
```
> apm --version
What is apm? I am a beginer.
```
OS name and version: Windows 10 64 bit
Platformio-ide-terminal version: 2.10.0 

### Additional Information

Text of error message below.
> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\Francis\AppData\Local\Temp\apm-install-dir-120229-10208-fzeya4.fgslvrt3xr\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

C:\Users\Francis\AppData\Local\Temp\apm-install-dir-120229-10208-fzeya4.fgslvrt3xr\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\Francis\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Francis\AppData\Local\atom\app-1.28.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\Francis\AppData\Local\Temp\apm-install-dir-120229-10208-fzeya4.fgslvrt3xr
`-- (empty)

npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
prebuild-install WARN install No prebuilt binaries found (target=2.0.5 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Francis\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\Francis\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\Francis\AppData\Local\atom\app-1.28.2\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Francis\\AppData\\Local\\atom\\app-1.28.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Francis\\AppData\\Local\\atom\\app-1.28.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Francis\AppData\Local\Temp\apm-install-dir-120229-10208-fzeya4.fgslvrt3xr\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Francis\AppData\Local\Temp\apm-install-dir-120229-10208-fzeya4.fgslvrt3xr\package.json'
npm WARN apm-install-dir-120229-10208-fzeya4.fgslvrt3xr No description
npm WARN apm-install-dir-120229-10208-fzeya4.fgslvrt3xr No repository field.
npm WARN apm-install-dir-120229-10208-fzeya4.fgslvrt3xr No README data
npm WARN apm-install-dir-120229-10208-fzeya4.fgslvrt3xr No license field.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Users\\Francis\\AppData\\Local\\atom\\app-1.28.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Francis\\AppData\\Local\\atom\\app-1.28.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Francis\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Francis\\.atom\\.apmrc" "install" "C:\\Users\\Francis\\AppData\\Local\\Temp\\d-120229-10208-1qj7rvp.rsdzwa5rk9\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script 'prebuild-install || node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty-prebuilt-multiarch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty-prebuilt-multiarch
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty-prebuilt-multiarch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Francis\AppData\Local\Temp\apm-install-dir-120229-10208-fzeya4.fgslvrt3xr\npm-debug.log
npm ERR! code 1
![temp-screenshot](https://user-images.githubusercontent.com/62837238/77856997-b6361280-7218-11ea-8102-1d9680658b96.jpg)

**Comment by alpha-i-am** [comment]
i think its a network error try again with a good network

**Comment by pranavwani** [comment]
Please try https://github.com/bus-stop/terminus

Fork of `platformio-atom-ide-terminal`
https://github.com/platformio/platformio-atom-ide-terminal/issues/872#issuecomment-658743370

**Comment by dshevanov** [comment]
> Please try https://github.com/bus-stop/terminus
> 
> Fork of `platformio-atom-ide-terminal`
> [#872 (comment)](https://github.com/platformio/platformio-atom-ide-terminal/issues/872#issuecomment-658743370)

Thank you so much dude

**Comment by williamklingler** [comment]
> Please try https://github.com/bus-stop/terminus
> 
> Fork of `platformio-atom-ide-terminal`
> [#872 (comment)](https://github.com/platformio/platformio-atom-ide-terminal/issues/872#issuecomment-658743370)

Terminus works beautifully, thank you

**Comment by Aerospace-Briefcase** [comment]
> > Please try https://github.com/bus-stop/terminus
> > Fork of `platformio-atom-ide-terminal`
> > [#872 (comment)](https://github.com/platformio/platformio-atom-ide-terminal/issues/872#issuecomment-658743370)
> 
> Terminus works beautifully, thank you

How to download it?. It's a zip file. How to import it to atom?

**Comment by the-j0k3r** [comment]
> How to download it?. It's a zip file. How to import it to atom?

@aerospace-briefcase

`apm install terminus`

Pls uninstall platfomio-ide-terminal or disable it so it doesn't conflict with terminus, **do not run them both at same time**.

**Comment by monishabtechit97** [comment]
I also faced the same problem. I tried everything what is above said...The only solution for this is to uninstall your atom and all the folders from the directory ..for eg.  .atom folder from your c drive. Again install atom and then install package platformio-ide terminal. It works for me.

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by the-j0k3r** [comment]
> This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

@ivankravets should archive the repo like he said before but there must be some interest on his part to want to keep this repo alive with 0 support.

Since he no longer replies to any emails or attempts of contact regarding this package the only alternative is to speculate which is what the assumption above is.

**Comment by ivankravets** [comment]
The latest version of platformio-ide-terminal should work on any machine. 

@UziTech, @UziTech we don't promote this extension and don't force people to use it. We don't make money on it. The main reason why do we keep it active is https://github.com/platformio/platformio-atom-ide that depends on `platformio-ide-terminal `. There is a small number of people who still use Atom for PlatformIO.

**Comment by the-j0k3r** [comment]
None makes money on any of these, I dont, in fact it costs me time (which is money) trying to steer ppl to supported projects, at least we provide ongoing support and bug fixes and I believe compatibility with Atom for PlatformIO.

Ppl alas will go for the extension with most downloads, which means nothing for how it works with current/future Atom.

>. There is a small number of people who still use Atom for PlatformIO.

At some stage since you dont actually fix bugs or provide support, you either have to care about those users to use supported projects or contribute code to said projects that will make it compatible with PlatformIO , if there is some special functionality that was left off from the fork/ js conversion. Even you yourself dont care about Atom as an editor.

Its always going to be a weird proposition, but currently its just frustrating to all involved.

thx for reply.

**Comment by UziTech** [comment]
> We don't promote this extension and don't force people to use it.

The problem is that you don't let people know that you won't fix bugs (or even respond to issues) in a timely manor (or at all). [x-terminal](https://atom.io/packages/x-terminal) does provide the `platformioIDETerminal` service and it wouldn't be hard to add it to [terminus](https://atom.io/packages/terminus) since it is a fork of this extension.

> We don't make money on it.

None of us get paid for this either but it doesn't take a lot of work to archive a repo, or put a message on the readme saying it is no longer maintained. I could even create a PR for the readme message and all you have to do is click a button.

**Comment by ivankravets** [comment]
Thanks. We will test x-terminal if it works with PlatformIO IDE. In any case, it looks like Atom has died:
- https://github.com/atom/atom/commits/master
- https://github.com/atom/atom/releases (1 maintenance release in 3 months)

**Comment by UziTech** [comment]
> it looks like Atom has died

I would say just based on how many people post issues to this repo Atom is not dead. It is not as popular as VS Code but is very much alive. And, for me at least, it works much better than VS Code.

P.S. the last commit from your link was 44 minutes ago, so I don't see how that can be considered dead. Based on your logic it looks like [platformio-core](https://github.com/platformio/platformio-core/releases) has died

**Comment by the-j0k3r** [comment]
>  it looks like Atom has died:

How can active and ongoing development (hours since last commits) be considered or mistaken as a dead project I wouldn't know, care to explain rationale?

Release schedule intervals also no indicator of death to any project, most popular large projects release every 6 months or some even once a year.

Terminus is a direct fork of this project at 2.1.0 and supports everything this project supports, backwards compatibility with foreign services has to be justified though, edge cases for a minority of users can be accommodated as long as all over the sudden we aren't providing support for 3rd party addons.

@uzitech, to archive a repo, all issues have to be closed, I can do that and assist @ivankravets since I do have access to this repo as a contributor and I did use to manage the issue tracker after support/dev was abandoned by the owner.
The only reason I haven't done so, is because the project owner stopped responding to contact attempts regarding archival of the repo which was what @ivankravets said he wanted to do.

However archiving repo, solves nothing, as long as the project is available for direct installation via Atom,

Readme additions will solve nothing because regular end users (the majority) dont read anything.
