### ISSUE TITLE
Atom 1.45.0 Installation Issue

### ISSUE THREAD

**Issue by 0xts** [platformio/platformio-atom-ide-terminal#841]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Description

I've been trying to install many terminal packages(expecting any which one to work) after updating my atom from 1.36 to 1.45 last night, but no terminal package seems to work. I was using atom-ide-terminal earlier and right after updating my atom to 1.45, it showed an incompatibility error, so I went ahead trying various other terminal packages that are available among which, my preferred(platformio-ide-terminal) showed up this error log:

![Screenshot from 2020-04-03 15-03-54](https://user-images.githubusercontent.com/20352977/78346244-63fc4500-75bc-11ea-9177-eccee0eef8af.png)

I'm unable to understand where exactly the issue is. Please help. Thanks.

### Steps to reproduce

1.Run "apm install platformio-ide-terminal"

**Expected behavior:** 
package to install and work properly

**Actual behavior:** 
gives an error while installation

**Reproduces how often:** 
100%

### Versions

```
> atom --version
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```
```
> apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.45.0
python 2.7.16
git 2.25.1
```
OS name and version: Kali Linux 4.17.0

**Comment by 0xts** [comment]
A similar issue was #770. However, it was python version related.

**Comment by cemkavuklu** [comment]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description
Trying to install @2.10.0 on Atom 1.45.0 to no avail. 


### Steps to reproduce

1. Run "apm install platformio-ide-terminal"


**Expected behavior:** 
Successful installation.

**Actual behavior:**
Installation fails.

**Reproduces how often:** 
100% of the time.

### Versions


```
> atom --version
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

```
> apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.45.0
python 2.7.17
git 2.20.1

```
OS name and version: Ubuntu 19.10
Platformio-ide-terminal version: 2.10.0


### Additional Information

node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /tmp/apm-install-dir-12034-23212-7fu7sz.xi1zq/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
prebuild-install || node scripts/install.js


Aborted (core dumped)
Aborted (core dumped)
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.3.0-45-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-12034-23212-7fu7sz.xi1zq/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Aborted (core dumped)
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-12034-23212-7fu7sz.xi1zq/package.json'
npm WARN apm-install-dir-12034-23212-7fu7sz.xi1zq No description
npm WARN apm-install-dir-12034-23212-7fu7sz.xi1zq No repository field.
npm WARN apm-install-dir-12034-23212-7fu7sz.xi1zq No README data
npm WARN apm-install-dir-12034-23212-7fu7sz.xi1zq No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cemkavuklu/.atom/.apm/_logs/2020-04-03T22_18_53_169Z-debug.log
